// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primtypes.djinni

package com.dropbox.djinni.test

data class AssortedPrimitives(
    val b: Boolean,
    val eight: Byte,
    val sixteen: Short,
    val thirtytwo: Int,
    val sixtyfour: Long,
    val fthirtytwo: Float,
    val fsixtyfour: Double,
    val oB: Boolean?,
    val oEight: Byte?,
    val oSixteen: Short?,
    val oThirtytwo: Int?,
    val oSixtyfour: Long?,
    val oFthirtytwo: Float?,
    val oFsixtyfour: Double?,
)
