// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primtypes.djinni

package com.dropbox.djinni.test

data class AssortedPrimitives(
    val mB: Boolean,
    val mEight: Byte,
    val mSixteen: Short,
    val mThirtytwo: Int,
    val mSixtyfour: Long,
    val mFthirtytwo: Float,
    val mFsixtyfour: Double,
    val mOB: Boolean?,
    val mOEight: Byte?,
    val mOSixteen: Short?,
    val mOThirtytwo: Int?,
    val mOSixtyfour: Long?,
    val mOFthirtytwo: Float?,
    val mOFsixtyfour: Double?,
)
