// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test

interface AsyncInterface {
    fun futureRoundtrip(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String>
}
