// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test

// Async DI surface for the audio engine (generated). Each provider is `suspend` so injection
// can await native readiness (AudioCoreInit) without blocking. Plain Kotlin -- NO DI framework
// here; a downstream graph @Includes this and (with Metro suspend-providers) turns each
// accessor into an async binding. Retrieve the impl via AudioCoreProviders.resolve().
interface AudioCoreProviders {
    suspend fun dataRefTest(): DataRefTest
    suspend fun reverseClientInterface(): ReverseClientInterface
    suspend fun protoTests(): ProtoTests
    suspend fun testOutcome(): TestOutcome
    suspend fun testDuration(): TestDuration
    suspend fun flagRoundtrip(): FlagRoundtrip
    suspend fun testArray(): TestArray
    suspend fun listenerCallerStatics(): ListenerCallerStatics
    suspend fun returnOneStatics(): ReturnOneStatics
    suspend fun returnTwoStatics(): ReturnTwoStatics
    suspend fun testHelpers(): TestHelpers
    suspend fun cppExceptionStatics(): CppExceptionStatics

    companion object
}
