// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test

/** Record returned by a client */
data class ClientReturnedRecord(
    val recordId: Long,
    val content: String,
    val misc: String?,
)
