// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test

/** Client interface */
interface ClientInterface {
    /** Returns record of given string */
    fun getRecord(recordId: Long, utf8string: String, misc: String?): ClientReturnedRecord
    fun identifierCheck(data: ByteArray, r: Int, jret: Long): Double
    fun returnStr(): String
    fun methTakingInterface(i: ClientInterface?): String
    fun methTakingOptionalInterface(i: ClientInterface?): String
}
