// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test

/**
 * Test for conflict of method name with an interface name.
 * See the comments about scopeSymbols in CppMarshal.scala for more info.
 */
interface Conflict {
}
