// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test

interface ConflictUser {
    fun Conflict(): Conflict?
    fun conflictArg(cs: Set<Conflict?>): Boolean
}
