// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

package com.dropbox.djinni.test

/** Record containing constants */
class Constants {

    companion object {
        /** bool_constant has documentation. */
        const val BOOL_CONSTANT: Boolean = true
        const val I8_CONSTANT: Byte = 1
        const val I16_CONSTANT: Short = 2
        const val I32_CONSTANT: Int = 3
        const val I64_CONSTANT: Long = 4L
        const val F32_CONSTANT: Float = 5.0f
        /**
         * f64_constant has long documentation.
         * (Second line of multi-line documentation.
         *   Indented third line of multi-line documentation.)
         */
        const val F64_CONSTANT: Double = 5.0
        val OPT_BOOL_CONSTANT: Boolean? = true
        val OPT_I8_CONSTANT: Byte? = 1
        /** opt_i16_constant has documentation. */
        val OPT_I16_CONSTANT: Short? = 2
        val OPT_I32_CONSTANT: Int? = 3
        val OPT_I64_CONSTANT: Long? = 4
        /**
         * opt_f32_constant has long documentation.
         * (Second line of multi-line documentation.
         *   Indented third line of multi-line documentation.)
         */
        val OPT_F32_CONSTANT: Float? = 5.0
        val OPT_F64_CONSTANT: Double? = 5.0
        const val STRING_CONSTANT: String = "string-constant"
        val OPT_STRING_CONSTANT: String? = "string-constant"
        val OBJECT_CONSTANT: ConstantRecord = ConstantRecord(
            someInteger = I32_CONSTANT,
            someString = STRING_CONSTANT
        )
        /**
         * No support for null optional constants
         * No support for optional constant records
         * No support for constant binary, list, set, map
         */
        const val DUMMY: Boolean = false
    }
}
