// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

package com.dropbox.djinni.test

/** Record for use in constants */
data class ConstantRecord(
    val someInteger: Int,
    val someString: String,
)
