// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test

/** Interface containing enum constant */
interface ConstantInterfaceWithEnum {

    companion object {
        val CONST_ENUM: ConstantEnum = ConstantEnum.SOME_VALUE
    }
}
