// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

package com.dropbox.djinni.test

// Injectable statics service for CppException (replaces language-level statics).
// Depend on THIS at call sites so the native surface stays hidden and mockable; a real
// instance comes from CppCppExceptionStatics (impl), whose construction is the init gate.
interface CppExceptionStatics {
    fun get(): CppException?
}
