// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

package com.dropbox.djinni.test

interface CppException {
    fun throwAnException(): Int
    fun callThrowingInterface(cb: ThrowingInterface?): Int
    fun callThrowingAndCatch(cb: ThrowingInterface?): String

    companion object {
    }
}
