// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from data_ref_view.djinni

package com.dropbox.djinni.test

interface DataRefTest {
    fun sendData(data: java.nio.ByteBuffer)
    fun retriveAsBin(): ByteArray
    fun sendMutableData(data: java.nio.ByteBuffer)
    fun generateData(): java.nio.ByteBuffer
    fun dataFromVec(): java.nio.ByteBuffer
    fun dataFromStr(): java.nio.ByteBuffer
    fun sendDataView(data: java.nio.ByteBuffer): ByteArray
    fun recvDataView(): java.nio.ByteBuffer

    companion object {
    }
}
