// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from data_ref_view.djinni

package com.dropbox.djinni.test

// Injectable statics service for DataRefTest (replaces language-level statics).
// Depend on THIS at call sites so the native surface stays hidden and mockable; a real
// instance comes from CppDataRefTestStatics (impl), whose construction is the init gate.
interface DataRefTestStatics {
    fun create(): DataRefTest
}
