// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

package com.dropbox.djinni.test

data class DateRecord(
    val mCreatedAt: java.util.Date,
) : Comparable<DateRecord> {

    override fun compareTo(other: DateRecord): Int {
        var tempResult: Int
        tempResult = this.mCreatedAt.compareTo(other.mCreatedAt)
        if (tempResult != 0) {
            return tempResult
        }
        return 0
    }
}
