// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

package com.dropbox.djinni.test

data class DateRecord(
    val createdAt: java.util.Date,
) : Comparable<DateRecord> {
    // TODO(kotlin-poc): port field-by-field compareTo from JavaGenerator for deriving(ord).
}
