// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

package com.dropbox.djinni.test

data class EnumUsageRecord(
    val e: Color,
    val o: Color?,
    val l: List<Color>,
    val s: Set<Color>,
    val m: Map<Color, Color>,
)
