// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

package com.dropbox.djinni.test

data class EnumUsageRecord(
    val mE: Color,
    val mO: Color?,
    val mL: List<Color>,
    val mS: Set<Color>,
    val mM: Map<Color, Color>,
)
