// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

package com.dropbox.djinni.test

interface EnumUsageInterface {
    fun e(e: Color): Color
    fun o(o: Color?): Color?
    fun l(l: List<Color>): List<Color>
    fun s(s: Set<Color>): Set<Color>
    fun m(m: Map<Color, Color>): Map<Color, Color>
}
