// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test

/** Extended record */
data class ExtendedRecord(
    val foo: Boolean,
) {

    companion object {
        val EXTENDED_RECORD_CONST: ExtendedRecord = ExtendedRecord(
            foo = true
        )
    }
}
