// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test

/** Used for ObjC multiple inheritance tests */
interface FirstListener {
    fun first()
}
