// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test

interface InterfaceUsingExtendedRecord {
    fun meth(er: ExtendedRecord): ExtendedRecord

    companion object {
        val CR: RecordUsingExtendedRecord = RecordUsingExtendedRecord(
            er = ExtendedRecord(
                foo = false
            )
        )
    }
}
