// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

package com.dropbox.djinni.test

data class MapDateRecord(
    val datesById: Map<String, java.util.Date>,
)
