// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

package com.dropbox.djinni.test

data class MapRecord(
    val map: Map<String, Long>,
    val imap: Map<Int, Int>,
)
