// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

package com.dropbox.djinni.test

data class NestedOutcome(
    val o: com.snapchat.djinni.Outcome<Int, String>,
)
