// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nested_collection.djinni

package com.dropbox.djinni.test

data class NestedCollection(
    val mSetList: List<Set<String>>,
)
