// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test

// Injectable statics service for ProtoTests (replaces language-level statics).
// Depend on THIS at call sites so the native surface stays hidden and mockable; a real
// instance comes from CppProtoTestsStatics (impl), whose construction is the init gate.
interface ProtoTestsStatics {
    fun protoToStrings(x: AddressBook): List<String>
    fun stringsToProto(x: List<String>): AddressBook
    fun embeddedProtoToString(x: RecordWithEmbeddedProto): String
    fun stringToEmbeddedProto(x: String): RecordWithEmbeddedProto
    fun cppProtoToString(x: PersistingState): String
    fun stringToCppProto(x: String): PersistingState
    fun embeddedCppProtoToString(x: RecordWithEmbeddedCppProto): String
    fun stringToEmbeddedCppProto(x: String): RecordWithEmbeddedCppProto
    fun protoListToStrings(x: List<Person>): List<String>
    fun stringsToProtoList(x: List<String>): List<Person>
    fun optionalProtoToString(x: Person?): String
    fun stringToOptionalProto(x: String): Person?
    fun stringToProtoOutcome(x: String): com.snapchat.djinni.Outcome<Person, Int>
}
