// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test

data class RecordWithFlags(
    val access: java.util.EnumSet<AccessFlags>,
)
