// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test

data class RecordWithNestedDerivings(
    val key: Int,
    val rec: RecordWithDerivings,
) : Comparable<RecordWithNestedDerivings> {
    // TODO(kotlin-poc): port field-by-field compareTo from JavaGenerator for deriving(ord).
}
