// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test

data class RecordWithNestedDerivings(
    val key: Int,
    val rec: RecordWithDerivings,
) : Comparable<RecordWithNestedDerivings> {

    override fun compareTo(other: RecordWithNestedDerivings): Int {
        var tempResult: Int
        tempResult = this.key.compareTo(other.key)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.rec.compareTo(other.rec)
        if (tempResult != 0) {
            return tempResult
        }
        return 0
    }
}
