// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test

data class RecordUsingExtendedRecord(
    val er: ExtendedRecord,
) {

    companion object {
        val CR: RecordUsingExtendedRecord = RecordUsingExtendedRecord(
            er = ExtendedRecord(
                foo = false
            )
        )
    }
}
