// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test

data class RecordWithDurationAndDerivings(
    val dt: java.time.Duration,
) : Comparable<RecordWithDurationAndDerivings> {
    // TODO(kotlin-poc): port field-by-field compareTo from JavaGenerator for deriving(ord).
}
