// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test

data class RecordWithDerivings(
    val eight: Byte,
    val sixteen: Short,
    val thirtytwo: Int,
    val sixtyfour: Long,
    val fthirtytwo: Float,
    val fsixtyfour: Double,
    val d: java.util.Date,
    val s: String,
) : Comparable<RecordWithDerivings> {
    // TODO(kotlin-poc): port field-by-field compareTo from JavaGenerator for deriving(ord).
}
