// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test

data class RecordWithNestedDerivings(
    val mKey: Int,
    val mRec: RecordWithDerivings,
) : Comparable<RecordWithNestedDerivings> {

    override fun compareTo(other: RecordWithNestedDerivings): Int {
        var tempResult: Int
        tempResult = this.mKey.compareTo(other.mKey)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.mRec.compareTo(other.mRec)
        if (tempResult != 0) {
            return tempResult
        }
        return 0
    }
}
