// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test

data class RecordWithDerivings(
    val mEight: Byte,
    val mSixteen: Short,
    val mThirtytwo: Int,
    val mSixtyfour: Long,
    val mFthirtytwo: Float,
    val mFsixtyfour: Double,
    val mD: java.util.Date,
    val mS: String,
) : Comparable<RecordWithDerivings> {

    override fun compareTo(other: RecordWithDerivings): Int {
        var tempResult: Int
        tempResult = this.mEight.compareTo(other.mEight)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.mSixteen.compareTo(other.mSixteen)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.mThirtytwo.compareTo(other.mThirtytwo)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.mSixtyfour.compareTo(other.mSixtyfour)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.mFthirtytwo.compareTo(other.mFthirtytwo)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.mFsixtyfour.compareTo(other.mFsixtyfour)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.mD.compareTo(other.mD)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.mS.compareTo(other.mS)
        if (tempResult != 0) {
            return tempResult
        }
        return 0
    }
}
