// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test

data class RecordWithDurationAndDerivings(
    val mDt: java.time.Duration,
) : Comparable<RecordWithDurationAndDerivings> {

    override fun compareTo(other: RecordWithDurationAndDerivings): Int {
        var tempResult: Int
        tempResult = this.mDt.compareTo(other.mDt)
        if (tempResult != 0) {
            return tempResult
        }
        return 0
    }
}
