// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test

data class RecordWithEmbeddedCppProto(
    val state: djinni.test2.Test2.PersistingState,
)
