// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test

data class RecordWithDerivings(
    val eight: Byte,
    val sixteen: Short,
    val thirtytwo: Int,
    val sixtyfour: Long,
    val fthirtytwo: Float,
    val fsixtyfour: Double,
    val d: java.util.Date,
    val s: String,
) : Comparable<RecordWithDerivings> {

    override fun compareTo(other: RecordWithDerivings): Int {
        var tempResult: Int
        tempResult = this.eight.compareTo(other.eight)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.sixteen.compareTo(other.sixteen)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.thirtytwo.compareTo(other.thirtytwo)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.sixtyfour.compareTo(other.sixtyfour)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.fthirtytwo.compareTo(other.fthirtytwo)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.fsixtyfour.compareTo(other.fsixtyfour)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.d.compareTo(other.d)
        if (tempResult != 0) {
            return tempResult
        }
        tempResult = this.s.compareTo(other.s)
        if (tempResult != 0) {
            return tempResult
        }
        return 0
    }
}
