// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test

data class RecordWithEmbeddedProto(
    val person: djinni.test.Test.Person,
)
