// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test

// Injectable statics service for ReturnOne (replaces language-level statics).
// Depend on THIS at call sites so the native surface stays hidden and mockable; a real
// instance comes from CppReturnOneStatics (impl), whose construction is the init gate.
interface ReturnOneStatics {
    fun getInstance(): ReturnOne
}
