// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test

/** Used for C++ multiple inheritance tests */
interface ReturnOne {
    fun returnOne(): Byte

    companion object {
    }
}
