// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test

interface ReverseClientInterface {
    fun returnStr(): String
    fun methTakingInterface(i: ReverseClientInterface?): String
    fun methTakingOptionalInterface(i: ReverseClientInterface?): String

    companion object {
    }
}
