// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test

// Injectable statics service for ReverseClientInterface (replaces language-level statics).
// Depend on THIS at call sites so the native surface stays hidden and mockable; a real
// instance comes from CppReverseClientInterfaceStatics (impl), whose construction is the init gate.
interface ReverseClientInterfaceStatics {
    fun create(): ReverseClientInterface
}
