// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test

/**
 * we need to test optional interface
 * this one will be used
 */
interface SampleInterface {
}
