// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

package com.dropbox.djinni.test

data class SetRecord(
    val mSet: Set<String>,
    val mIset: Set<Int>,
)
