// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test

// Injectable statics service for TestHelpers (replaces language-level statics).
// Depend on THIS at call sites so the native surface stays hidden and mockable; a real
// instance comes from CppTestHelpersStatics (impl), whose construction is the init gate.
interface TestHelpersStatics {
    /** Method with documentation */
    fun getSetRecord(): SetRecord
    /**
     * Method with long documentation
     * (Second line of multi-line documentation.
     *   Indented third line of multi-line documentation.)
     */
    fun checkSetRecord(rec: SetRecord): Boolean
    fun getPrimitiveList(): PrimitiveList
    fun checkPrimitiveList(pl: PrimitiveList): Boolean
    fun getNestedCollection(): NestedCollection
    fun checkNestedCollection(nc: NestedCollection): Boolean
    fun getMap(): Map<String, Long>
    fun checkMap(m: Map<String, Long>): Boolean
    fun getEmptyMap(): Map<String, Long>
    fun checkEmptyMap(m: Map<String, Long>): Boolean
    fun getMapListRecord(): MapListRecord
    fun checkMapListRecord(m: MapListRecord): Boolean
    fun checkClientInterfaceAscii(i: ClientInterface?)
    fun checkClientInterfaceNonascii(i: ClientInterface?)
    fun checkClientInterfaceArgs(i: ClientInterface?)
    fun checkEnumMap(m: Map<Color, String>)
    fun checkEnum(c: Color)
    fun tokenId(t: UserToken?): UserToken?
    fun createCppToken(): UserToken
    fun checkCppToken(t: UserToken?)
    fun cppTokenId(t: UserToken?): Long
    fun checkTokenType(t: UserToken?, type: String)
    fun returnNone(): Int?
    /** Ensures that we generate integer translation code */
    fun assortedPrimitivesId(i: AssortedPrimitives): AssortedPrimitives
    fun idBinary(b: ByteArray): ByteArray
    fun getAsyncResult(): com.snapchat.djinni.Future<Int>
    fun futureRoundtrip(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String>
    fun asyncEarlyThrow(): com.snapchat.djinni.Future<Int>
    fun voidAsyncMethod(f: com.snapchat.djinni.Future<Unit>): com.snapchat.djinni.Future<Unit>
    /**
     * If the input is empty, returns back an empty future.
     * If the input is non-empty, returns back the value plus one.
     */
    fun addOneIfPresent(f: com.snapchat.djinni.Future<Int?>): com.snapchat.djinni.Future<Int?>
    /** try-catches the future f, and accesses the error message, and returns as a string. */
    fun returnExceptionString(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String>
    fun checkAsyncInterface(i: AsyncInterface?): com.snapchat.djinni.Future<String>
    fun checkAsyncComposition(i: AsyncInterface?): com.snapchat.djinni.Future<String>
    fun getOptionalList(): List<String?>
    fun checkOptionalList(ol: List<String?>): Boolean
    fun getOptionalSet(): Set<String?>
    fun checkOptionalSet(os: Set<String?>): Boolean
    fun getOptionalMap(): Map<String?, String?>
    fun checkOptionalMap(om: Map<String?, String?>): Boolean
}
