// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test

// Injectable statics service for TestArray (replaces language-level statics).
// Depend on THIS at call sites so the native surface stays hidden and mockable; a real
// instance comes from CppTestArrayStatics (impl), whose construction is the init gate.
interface TestArrayStatics {
    fun testStringArray(a: Array<String>): Array<String>
    fun testIntArray(a: IntArray): IntArray
    fun testRecordArray(a: Array<Vec2>): Array<Vec2>
    fun testArrayOfArray(a: Array<IntArray>): Array<IntArray>
}
