// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test

// Static-only utility surface, exposed as an injectable service (no language-level statics).
// Depend on THIS at call sites so the native surface stays hidden and mockable; a real
// instance comes from CppTestDurationStatics (impl), whose construction is the init gate.
interface TestDuration {
    fun hoursString(dt: java.time.Duration): String
    fun minutesString(dt: java.time.Duration): String
    fun secondsString(dt: java.time.Duration): String
    fun millisString(dt: java.time.Duration): String
    fun microsString(dt: java.time.Duration): String
    fun nanosString(dt: java.time.Duration): String
    fun hours(count: Int): java.time.Duration
    fun minutes(count: Int): java.time.Duration
    fun seconds(count: Int): java.time.Duration
    fun millis(count: Int): java.time.Duration
    fun micros(count: Int): java.time.Duration
    fun nanos(count: Int): java.time.Duration
    fun hoursf(count: Double): java.time.Duration
    fun minutesf(count: Double): java.time.Duration
    fun secondsf(count: Double): java.time.Duration
    fun millisf(count: Double): java.time.Duration
    fun microsf(count: Double): java.time.Duration
    fun nanosf(count: Double): java.time.Duration
    fun box(count: Long): java.time.Duration?
    fun unbox(dt: java.time.Duration?): Long

    companion object {
    }
}
