// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from single_language_interfaces.djinni

package com.dropbox.djinni.test

/**
 * Generating and compiling this makes sure other languages don't break
 * on references to interfaces they don't need.
 */
interface UsesSingleLanguageListeners {
    fun callForObjC(l: ObjcOnlyListener?)
    fun returnForObjC(): ObjcOnlyListener?
    fun callForJava(l: JavaOnlyListener?)
    fun returnForJava(): JavaOnlyListener?
}
