// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

package com.dropbox.djinni.test

interface VarnameInterface {
    /**
     * We should also rewrite parameter names in docstrings.
     * RArg should be rewritten.
     * _i_arg_ should not.
     */
    fun Rmethod(RArg: VarnameRecord): VarnameRecord
    fun Imethod(IArg: VarnameInterface?): VarnameInterface?
}
