// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test

// Impl of AudioCoreProviders (hidden -- consumers only see the interface + resolve()).
// Each provider awaits AudioCoreInit, then delegates to the shared internal Cpp<name>Statics
// singleton (the same statics facade the compat hatch uses). No Cpp* type is ever exposed.
internal object AudioCoreProvidersImpl : AudioCoreProviders {
    override suspend fun dataRefTest(): DataRefTest {
        AudioCoreInit.awaitReady()
        return CppDataRefTestStatics.create()
    }

    override suspend fun reverseClientInterface(): ReverseClientInterface {
        AudioCoreInit.awaitReady()
        return CppReverseClientInterfaceStatics.create()
    }

    override suspend fun protoTests(): ProtoTests {
        AudioCoreInit.awaitReady()
        return CppProtoTestsStatics
    }

    override suspend fun testOutcome(): TestOutcome {
        AudioCoreInit.awaitReady()
        return CppTestOutcomeStatics
    }

    override suspend fun testDuration(): TestDuration {
        AudioCoreInit.awaitReady()
        return CppTestDurationStatics
    }

    override suspend fun flagRoundtrip(): FlagRoundtrip {
        AudioCoreInit.awaitReady()
        return CppFlagRoundtripStatics
    }

    override suspend fun testArray(): TestArray {
        AudioCoreInit.awaitReady()
        return CppTestArrayStatics
    }

    override suspend fun listenerCallerStatics(): ListenerCallerStatics {
        AudioCoreInit.awaitReady()
        return CppListenerCallerStatics
    }

    override suspend fun returnOneStatics(): ReturnOneStatics {
        AudioCoreInit.awaitReady()
        return CppReturnOneStatics
    }

    override suspend fun returnTwoStatics(): ReturnTwoStatics {
        AudioCoreInit.awaitReady()
        return CppReturnTwoStatics
    }

    override suspend fun testHelpers(): TestHelpers {
        AudioCoreInit.awaitReady()
        return CppTestHelpersStatics
    }

    override suspend fun cppExceptionStatics(): CppExceptionStatics {
        AudioCoreInit.awaitReady()
        return CppCppExceptionStatics
    }
}

// Retrieval (cheap; no construction) -- hand the interface to a downstream DI graph.
fun AudioCoreProviders.Companion.resolve(): AudioCoreProviders = AudioCoreProvidersImpl
