// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test

import kotlinx.coroutines.CompletableDeferred

// Readiness gate for the native audio-engine .so. The app calls markReady() once the
// library is loaded + initialized (or markFailed(cause) on failure); every generated
// provider / compat hatch awaits this before touching the native surface, so no native
// call can run before the engine is ready.
object AudioCoreInit {
    private val ready = CompletableDeferred<Unit>()

    // Non-suspend snapshot: true once initialized SUCCESSFULLY (completed & not failed).
    val isReady: Boolean get() = ready.isCompleted && !ready.isCancelled

    // Suspends until the engine is ready; throws if initialization failed.
    suspend fun awaitReady() = ready.await()

    // Signal the .so is loaded + initialized. Idempotent (a later call is a no-op).
    fun markReady() { ready.complete(Unit) }

    // Signal initialization failed -- awaiters (and blocking hatches) throw `cause` instead
    // of hanging forever.
    fun markFailed(cause: Throwable) { ready.completeExceptionally(cause) }
}
