// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

package com.dropbox.djinni.test

// Internal singleton for the CppException static surface -- never visible to consumers. Reached only
// via the Companion hatch (legacy) + AudioCoreProviders. Stateless facade over the native
// statics; readiness gating lives at those seams (AudioCoreInit), not here.
internal object CppCppExceptionStatics : CppExceptionStatics {

    override fun get(): CppException? = get_native()
    private external fun get_native(): CppException?
}
