// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

// CppProxy for ConflictUser -- wraps a native C++ implementation. Instance methods only;
// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members
// the JNI layer / support-lib bind to. Static factories live on CppConflictUserStatics.
class CppConflictUser private constructor(private val nativeRef: Long) : ConflictUser {
    private val destroyed = AtomicBoolean(false)

    init {
        if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
        NativeObjectManager.register(this, nativeRef)
    }

    override fun Conflict(): Conflict? {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_Conflict(nativeRef)
    }
    private external fun native_Conflict(_nativeRef: Long): Conflict?

    override fun conflictArg(cs: Set<Conflict?>): Boolean {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_conflictArg(nativeRef, cs)
    }
    private external fun native_conflictArg(_nativeRef: Long, cs: Set<Conflict?>): Boolean

    companion object {
        @JvmStatic
        external fun nativeDestroy(nativeRef: Long)
    }
}
