// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

// CppProxy for CppException -- wraps a native C++ implementation. Instance methods only;
// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members
// the JNI layer / support-lib bind to. Static factories live on CppCppExceptionStatics.
class CppCppException private constructor(private val nativeRef: Long) : CppException {
    private val destroyed = AtomicBoolean(false)

    init {
        if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
        NativeObjectManager.register(this, nativeRef)
    }

    override fun throwAnException(): Int {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_throwAnException(nativeRef)
    }
    private external fun native_throwAnException(_nativeRef: Long): Int

    override fun callThrowingInterface(cb: ThrowingInterface?): Int {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_callThrowingInterface(nativeRef, cb)
    }
    private external fun native_callThrowingInterface(_nativeRef: Long, cb: ThrowingInterface?): Int

    override fun callThrowingAndCatch(cb: ThrowingInterface?): String {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_callThrowingAndCatch(nativeRef, cb)
    }
    private external fun native_callThrowingAndCatch(_nativeRef: Long, cb: ThrowingInterface?): String

    companion object {
        @JvmStatic
        external fun nativeDestroy(nativeRef: Long)
    }
}
