// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

// CppProxy for ConstantInterfaceWithEnum -- wraps a native C++ implementation. Instance methods only;
// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members
// the JNI layer / support-lib bind to. Static factories live on CppConstantInterfaceWithEnumStatics.
internal class CppConstantInterfaceWithEnum private constructor(private val nativeRef: Long) : ConstantInterfaceWithEnum {
    private val destroyed = AtomicBoolean(false)

    init {
        if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
        NativeObjectManager.register(this, nativeRef)
    }

    companion object {
        @JvmStatic
        external fun nativeDestroy(nativeRef: Long)
    }
}
