// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

// CppProxy for ConstantsInterface -- wraps a native C++ implementation. Instance methods only;
// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members
// the JNI layer / support-lib bind to. Static factories live on CppConstantsInterfaceStatics.
internal class CppConstantsInterface private constructor(private val nativeRef: Long) : ConstantsInterface {
    private val destroyed = AtomicBoolean(false)

    init {
        if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
        NativeObjectManager.register(this, nativeRef)
    }

    override fun dummy() {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        native_dummy(nativeRef)
    }
    private external fun native_dummy(_nativeRef: Long)

    companion object {
        @JvmStatic
        external fun nativeDestroy(nativeRef: Long)
    }
}
