// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from data_ref_view.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

// CppProxy for DataRefTest -- wraps a native C++ implementation. Instance methods only;
// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members
// the JNI layer / support-lib bind to. Static factories live on CppDataRefTestStatics.
internal class CppDataRefTest private constructor(private val nativeRef: Long) : DataRefTest {
    private val destroyed = AtomicBoolean(false)

    init {
        if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
        NativeObjectManager.register(this, nativeRef)
    }

    override fun sendData(data: java.nio.ByteBuffer) {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        native_sendData(nativeRef, data)
    }
    private external fun native_sendData(_nativeRef: Long, data: java.nio.ByteBuffer)

    override fun retriveAsBin(): ByteArray {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_retriveAsBin(nativeRef)
    }
    private external fun native_retriveAsBin(_nativeRef: Long): ByteArray

    override fun sendMutableData(data: java.nio.ByteBuffer) {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        native_sendMutableData(nativeRef, data)
    }
    private external fun native_sendMutableData(_nativeRef: Long, data: java.nio.ByteBuffer)

    override fun generateData(): java.nio.ByteBuffer {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_generateData(nativeRef)
    }
    private external fun native_generateData(_nativeRef: Long): java.nio.ByteBuffer

    override fun dataFromVec(): java.nio.ByteBuffer {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_dataFromVec(nativeRef)
    }
    private external fun native_dataFromVec(_nativeRef: Long): java.nio.ByteBuffer

    override fun dataFromStr(): java.nio.ByteBuffer {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_dataFromStr(nativeRef)
    }
    private external fun native_dataFromStr(_nativeRef: Long): java.nio.ByteBuffer

    override fun sendDataView(data: java.nio.ByteBuffer): ByteArray {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_sendDataView(nativeRef, data)
    }
    private external fun native_sendDataView(_nativeRef: Long, data: java.nio.ByteBuffer): ByteArray

    override fun recvDataView(): java.nio.ByteBuffer {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_recvDataView(nativeRef)
    }
    private external fun native_recvDataView(_nativeRef: Long): java.nio.ByteBuffer

    companion object {
        @JvmStatic
        external fun nativeDestroy(nativeRef: Long)
    }
}
