// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from data_ref_view.djinni

package com.dropbox.djinni.test

// Internal singleton for the DataRefTest static surface -- never visible to consumers. Reached only
// via the Companion hatch (legacy) + AudioCoreProviders. Stateless facade over the native
// statics; readiness gating lives at those seams (AudioCoreInit), not here.
internal object CppDataRefTestStatics {

    fun create(): DataRefTest =
        create_native() ?: throw IllegalStateException("DataRefTest.create returned null")
    private external fun create_native(): DataRefTest?
}
