// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from data_ref_view.djinni

package com.dropbox.djinni.test

// Impl of DataRefTestStatics. Constructing this is the SINGLE place the native surface becomes
// reachable, so it is the natural init gate: put your 'ensure .so loaded + initialized' hook
// in the init block below. Kept as an injection seam -- the generator imposes no policy.
class CppDataRefTestStatics : DataRefTestStatics {
    init {
        // INIT SEAM: ensure the native library is loaded/initialized here (app-injected),
        // e.g. AudioCoreLib.load(). Left unspecified so no init policy is baked into codegen.
    }

    override fun create(): DataRefTest =
        create_native() ?: throw IllegalStateException("DataRefTest.create returned null")
    private external fun create_native(): DataRefTest?
}
