// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `CppException.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppCppExceptionStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: CppExceptionStatics by lazy(LazyThreadSafetyMode.NONE) { CppCppExceptionStatics() }

fun CppException.Companion.get(): CppException = instance.get()
