// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

package com.dropbox.djinni.test

import kotlinx.coroutines.runBlocking

// Source-compat hatch: old `CppException.<static>(...)` call sites keep compiling -- now init-SAFE.
// Each hatch blocks on AudioCore readiness before touching the native surface, so a pre-init
// call WAITS instead of crashing (old code pays with a blocked thread; new code should migrate
// to the suspend AudioCoreProviders). Delegates to the internal CppCppExceptionStatics singleton (also reused
// by AudioCoreProvidersImpl).

fun CppException.Companion.get(): CppException? {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppCppExceptionStatics.get()
}
