// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

// CppProxy for EnumUsageInterface -- wraps a native C++ implementation. Instance methods only;
// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members
// the JNI layer / support-lib bind to. Static factories live on CppEnumUsageInterfaceStatics.
internal class CppEnumUsageInterface private constructor(private val nativeRef: Long) : EnumUsageInterface {
    private val destroyed = AtomicBoolean(false)

    init {
        if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
        NativeObjectManager.register(this, nativeRef)
    }

    override fun e(e: Color): Color {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_e(nativeRef, e)
    }
    private external fun native_e(_nativeRef: Long, e: Color): Color

    override fun o(o: Color?): Color? {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_o(nativeRef, o)
    }
    private external fun native_o(_nativeRef: Long, o: Color?): Color?

    override fun l(l: List<Color>): List<Color> {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_l(nativeRef, l)
    }
    private external fun native_l(_nativeRef: Long, l: List<Color>): List<Color>

    override fun s(s: Set<Color>): Set<Color> {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_s(nativeRef, s)
    }
    private external fun native_s(_nativeRef: Long, s: Set<Color>): Set<Color>

    override fun m(m: Map<Color, Color>): Map<Color, Color> {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_m(nativeRef, m)
    }
    private external fun native_m(_nativeRef: Long, m: Map<Color, Color>): Map<Color, Color>

    companion object {
        @JvmStatic
        external fun nativeDestroy(nativeRef: Long)
    }
}
