// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test

// Impl of FlagRoundtripStatics. Constructing this is the SINGLE place the native surface becomes
// reachable, so it is the natural init gate: put your 'ensure .so loaded + initialized' hook
// in the init block below. Kept as an injection seam -- the generator imposes no policy.
class CppFlagRoundtripStatics : FlagRoundtripStatics {
    init {
        // INIT SEAM: ensure the native library is loaded/initialized here (app-injected),
        // e.g. AudioCoreLib.load(). Left unspecified so no init policy is baked into codegen.
    }

    override fun roundtripAccess(flag: java.util.EnumSet<AccessFlags>): java.util.EnumSet<AccessFlags> = roundtripAccess_native(flag)
    private external fun roundtripAccess_native(flag: java.util.EnumSet<AccessFlags>): java.util.EnumSet<AccessFlags>

    override fun roundtripEmpty(flag: java.util.EnumSet<EmptyFlags>): java.util.EnumSet<EmptyFlags> = roundtripEmpty_native(flag)
    private external fun roundtripEmpty_native(flag: java.util.EnumSet<EmptyFlags>): java.util.EnumSet<EmptyFlags>

    override fun roundtripAccessBoxed(flag: java.util.EnumSet<AccessFlags>?): java.util.EnumSet<AccessFlags>? = roundtripAccessBoxed_native(flag)
    private external fun roundtripAccessBoxed_native(flag: java.util.EnumSet<AccessFlags>?): java.util.EnumSet<AccessFlags>?

    override fun roundtripEmptyBoxed(flag: java.util.EnumSet<EmptyFlags>?): java.util.EnumSet<EmptyFlags>? = roundtripEmptyBoxed_native(flag)
    private external fun roundtripEmptyBoxed_native(flag: java.util.EnumSet<EmptyFlags>?): java.util.EnumSet<EmptyFlags>?
}
