// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test

// Internal singleton for the FlagRoundtrip static surface -- never visible to consumers. Reached only
// via the Companion hatch (legacy) + AudioCoreProviders. Stateless facade over the native
// statics; readiness gating lives at those seams (AudioCoreInit), not here.
internal object CppFlagRoundtripStatics : FlagRoundtrip {

    override fun roundtripAccess(flag: java.util.EnumSet<AccessFlags>): java.util.EnumSet<AccessFlags> = roundtripAccess_native(flag)
    private external fun roundtripAccess_native(flag: java.util.EnumSet<AccessFlags>): java.util.EnumSet<AccessFlags>

    override fun roundtripEmpty(flag: java.util.EnumSet<EmptyFlags>): java.util.EnumSet<EmptyFlags> = roundtripEmpty_native(flag)
    private external fun roundtripEmpty_native(flag: java.util.EnumSet<EmptyFlags>): java.util.EnumSet<EmptyFlags>

    override fun roundtripAccessBoxed(flag: java.util.EnumSet<AccessFlags>?): java.util.EnumSet<AccessFlags>? = roundtripAccessBoxed_native(flag)
    private external fun roundtripAccessBoxed_native(flag: java.util.EnumSet<AccessFlags>?): java.util.EnumSet<AccessFlags>?

    override fun roundtripEmptyBoxed(flag: java.util.EnumSet<EmptyFlags>?): java.util.EnumSet<EmptyFlags>? = roundtripEmptyBoxed_native(flag)
    private external fun roundtripEmptyBoxed_native(flag: java.util.EnumSet<EmptyFlags>?): java.util.EnumSet<EmptyFlags>?
}
