// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

// CppProxy for InterfaceUsingExtendedRecord -- wraps a native C++ implementation. Instance methods only;
// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members
// the JNI layer / support-lib bind to. Static factories live on CppInterfaceUsingExtendedRecordStatics.
class CppInterfaceUsingExtendedRecord private constructor(private val nativeRef: Long) : InterfaceUsingExtendedRecord {
    private val destroyed = AtomicBoolean(false)

    init {
        if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
        NativeObjectManager.register(this, nativeRef)
    }

    override fun meth(er: ExtendedRecord): ExtendedRecord {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_meth(nativeRef, er)
    }
    private external fun native_meth(_nativeRef: Long, er: ExtendedRecord): ExtendedRecord

    companion object {
        @JvmStatic
        external fun nativeDestroy(nativeRef: Long)
    }
}
