// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

// CppProxy for ListenerCaller -- wraps a native C++ implementation. Instance methods only;
// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members
// the JNI layer / support-lib bind to. Static factories live on CppListenerCallerStatics.
internal class CppListenerCaller private constructor(private val nativeRef: Long) : ListenerCaller {
    private val destroyed = AtomicBoolean(false)

    init {
        if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
        NativeObjectManager.register(this, nativeRef)
    }

    override fun callFirst() {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        native_callFirst(nativeRef)
    }
    private external fun native_callFirst(_nativeRef: Long)

    override fun callSecond() {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        native_callSecond(nativeRef)
    }
    private external fun native_callSecond(_nativeRef: Long)

    companion object {
        @JvmStatic
        external fun nativeDestroy(nativeRef: Long)
    }
}
