// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test

// Internal singleton for the ListenerCaller static surface -- never visible to consumers. Reached only
// via the Companion hatch (legacy) + AudioCoreProviders. Stateless facade over the native
// statics; readiness gating lives at those seams (AudioCoreInit), not here.
internal object CppListenerCallerStatics : ListenerCallerStatics {

    override fun init(firstL: FirstListener?, secondL: SecondListener?): ListenerCaller? = init_native(firstL, secondL)
    private external fun init_native(firstL: FirstListener?, secondL: SecondListener?): ListenerCaller?
}
