// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test

// Internal singleton for the ProtoTests static surface -- never visible to consumers. Reached only
// via the Companion hatch (legacy) + AudioCoreProviders. Stateless facade over the native
// statics; readiness gating lives at those seams (AudioCoreInit), not here.
internal object CppProtoTestsStatics : ProtoTests {

    override fun protoToStrings(x: djinni.test.Test.AddressBook): List<String> = protoToStrings_native(x)
    private external fun protoToStrings_native(x: djinni.test.Test.AddressBook): List<String>

    override fun stringsToProto(x: List<String>): djinni.test.Test.AddressBook = stringsToProto_native(x)
    private external fun stringsToProto_native(x: List<String>): djinni.test.Test.AddressBook

    override fun embeddedProtoToString(x: RecordWithEmbeddedProto): String = embeddedProtoToString_native(x)
    private external fun embeddedProtoToString_native(x: RecordWithEmbeddedProto): String

    override fun stringToEmbeddedProto(x: String): RecordWithEmbeddedProto = stringToEmbeddedProto_native(x)
    private external fun stringToEmbeddedProto_native(x: String): RecordWithEmbeddedProto

    override fun cppProtoToString(x: djinni.test2.Test2.PersistingState): String = cppProtoToString_native(x)
    private external fun cppProtoToString_native(x: djinni.test2.Test2.PersistingState): String

    override fun stringToCppProto(x: String): djinni.test2.Test2.PersistingState = stringToCppProto_native(x)
    private external fun stringToCppProto_native(x: String): djinni.test2.Test2.PersistingState

    override fun embeddedCppProtoToString(x: RecordWithEmbeddedCppProto): String = embeddedCppProtoToString_native(x)
    private external fun embeddedCppProtoToString_native(x: RecordWithEmbeddedCppProto): String

    override fun stringToEmbeddedCppProto(x: String): RecordWithEmbeddedCppProto = stringToEmbeddedCppProto_native(x)
    private external fun stringToEmbeddedCppProto_native(x: String): RecordWithEmbeddedCppProto

    override fun protoListToStrings(x: List<djinni.test.Test.Person>): List<String> = protoListToStrings_native(x)
    private external fun protoListToStrings_native(x: List<djinni.test.Test.Person>): List<String>

    override fun stringsToProtoList(x: List<String>): List<djinni.test.Test.Person> = stringsToProtoList_native(x)
    private external fun stringsToProtoList_native(x: List<String>): List<djinni.test.Test.Person>

    override fun optionalProtoToString(x: djinni.test.Test.Person?): String = optionalProtoToString_native(x)
    private external fun optionalProtoToString_native(x: djinni.test.Test.Person?): String

    override fun stringToOptionalProto(x: String): djinni.test.Test.Person? = stringToOptionalProto_native(x)
    private external fun stringToOptionalProto_native(x: String): djinni.test.Test.Person?

    override fun stringToProtoOutcome(x: String): com.snapchat.djinni.Outcome<djinni.test.Test.Person, Int> = stringToProtoOutcome_native(x)
    private external fun stringToProtoOutcome_native(x: String): com.snapchat.djinni.Outcome<djinni.test.Test.Person, Int>
}
