// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test

// Impl of ProtoTestsStatics. Constructing this is the SINGLE place the native surface becomes
// reachable, so it is the natural init gate: put your 'ensure .so loaded + initialized' hook
// in the init block below. Kept as an injection seam -- the generator imposes no policy.
class CppProtoTestsStatics : ProtoTestsStatics {
    init {
        // INIT SEAM: ensure the native library is loaded/initialized here (app-injected),
        // e.g. AudioCoreLib.load(). Left unspecified so no init policy is baked into codegen.
    }

    override fun protoToStrings(x: AddressBook): List<String> = protoToStrings_native(x)
    private external fun protoToStrings_native(x: AddressBook): List<String>

    override fun stringsToProto(x: List<String>): AddressBook = stringsToProto_native(x)
    private external fun stringsToProto_native(x: List<String>): AddressBook

    override fun embeddedProtoToString(x: RecordWithEmbeddedProto): String = embeddedProtoToString_native(x)
    private external fun embeddedProtoToString_native(x: RecordWithEmbeddedProto): String

    override fun stringToEmbeddedProto(x: String): RecordWithEmbeddedProto = stringToEmbeddedProto_native(x)
    private external fun stringToEmbeddedProto_native(x: String): RecordWithEmbeddedProto

    override fun cppProtoToString(x: PersistingState): String = cppProtoToString_native(x)
    private external fun cppProtoToString_native(x: PersistingState): String

    override fun stringToCppProto(x: String): PersistingState = stringToCppProto_native(x)
    private external fun stringToCppProto_native(x: String): PersistingState

    override fun embeddedCppProtoToString(x: RecordWithEmbeddedCppProto): String = embeddedCppProtoToString_native(x)
    private external fun embeddedCppProtoToString_native(x: RecordWithEmbeddedCppProto): String

    override fun stringToEmbeddedCppProto(x: String): RecordWithEmbeddedCppProto = stringToEmbeddedCppProto_native(x)
    private external fun stringToEmbeddedCppProto_native(x: String): RecordWithEmbeddedCppProto

    override fun protoListToStrings(x: List<Person>): List<String> = protoListToStrings_native(x)
    private external fun protoListToStrings_native(x: List<Person>): List<String>

    override fun stringsToProtoList(x: List<String>): List<Person> = stringsToProtoList_native(x)
    private external fun stringsToProtoList_native(x: List<String>): List<Person>

    override fun optionalProtoToString(x: Person?): String = optionalProtoToString_native(x)
    private external fun optionalProtoToString_native(x: Person?): String

    override fun stringToOptionalProto(x: String): Person? = stringToOptionalProto_native(x)
    private external fun stringToOptionalProto_native(x: String): Person?

    override fun stringToProtoOutcome(x: String): com.snapchat.djinni.Outcome<Person, Int> = stringToProtoOutcome_native(x)
    private external fun stringToProtoOutcome_native(x: String): com.snapchat.djinni.Outcome<Person, Int>
}
