// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test

// Internal singleton for the ReverseClientInterface static surface -- never visible to consumers. Reached only
// via the Companion hatch (legacy) + AudioCoreProviders. Stateless facade over the native
// statics; readiness gating lives at those seams (AudioCoreInit), not here.
internal object CppReverseClientInterfaceStatics {

    fun create(): ReverseClientInterface =
        create_native() ?: throw IllegalStateException("reverse_client_interface.create returned null")
    private external fun create_native(): ReverseClientInterface?
}
