// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

// CppProxy for ReturnOne -- wraps a native C++ implementation. Instance methods only;
// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members
// the JNI layer / support-lib bind to. Static factories live on CppReturnOneStatics.
internal class CppReturnOne private constructor(private val nativeRef: Long) : ReturnOne {
    private val destroyed = AtomicBoolean(false)

    init {
        if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
        NativeObjectManager.register(this, nativeRef)
    }

    override fun returnOne(): Byte {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_returnOne(nativeRef)
    }
    private external fun native_returnOne(_nativeRef: Long): Byte

    companion object {
        @JvmStatic
        external fun nativeDestroy(nativeRef: Long)
    }
}
