// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test

// Internal singleton for the ReturnOne static surface -- never visible to consumers. Reached only
// via the Companion hatch (legacy) + AudioCoreProviders. Stateless facade over the native
// statics; readiness gating lives at those seams (AudioCoreInit), not here.
internal object CppReturnOneStatics : ReturnOneStatics {

    override fun getInstance(): ReturnOne? = getInstance_native()
    private external fun getInstance_native(): ReturnOne?
}
