// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

package com.dropbox.djinni.test

// Impl of TestOutcomeStatics. Constructing this is the SINGLE place the native surface becomes
// reachable, so it is the natural init gate: put your 'ensure .so loaded + initialized' hook
// in the init block below. Kept as an injection seam -- the generator imposes no policy.
class CppTestOutcomeStatics : TestOutcomeStatics {
    init {
        // INIT SEAM: ensure the native library is loaded/initialized here (app-injected),
        // e.g. AudioCoreLib.load(). Left unspecified so no init policy is baked into codegen.
    }

    override fun getSuccessOutcome(): com.snapchat.djinni.Outcome<String, Int> = getSuccessOutcome_native()
    private external fun getSuccessOutcome_native(): com.snapchat.djinni.Outcome<String, Int>

    override fun getErrorOutcome(): com.snapchat.djinni.Outcome<String, Int> = getErrorOutcome_native()
    private external fun getErrorOutcome_native(): com.snapchat.djinni.Outcome<String, Int>

    override fun putSuccessOutcome(x: com.snapchat.djinni.Outcome<String, Int>): String = putSuccessOutcome_native(x)
    private external fun putSuccessOutcome_native(x: com.snapchat.djinni.Outcome<String, Int>): String

    override fun putErrorOutcome(x: com.snapchat.djinni.Outcome<String, Int>): Int = putErrorOutcome_native(x)
    private external fun putErrorOutcome_native(x: com.snapchat.djinni.Outcome<String, Int>): Int

    override fun getNestedSuccessOutcome(): NestedOutcome = getNestedSuccessOutcome_native()
    private external fun getNestedSuccessOutcome_native(): NestedOutcome

    override fun getNestedErrorOutcome(): NestedOutcome = getNestedErrorOutcome_native()
    private external fun getNestedErrorOutcome_native(): NestedOutcome

    override fun putNestedSuccessOutcome(x: NestedOutcome): Int = putNestedSuccessOutcome_native(x)
    private external fun putNestedSuccessOutcome_native(x: NestedOutcome): Int

    override fun putNestedErrorOutcome(x: NestedOutcome): String = putNestedErrorOutcome_native(x)
    private external fun putNestedErrorOutcome_native(x: NestedOutcome): String
}
