// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test

// Impl of TestDurationStatics. Constructing this is the SINGLE place the native surface becomes
// reachable, so it is the natural init gate: put your 'ensure .so loaded + initialized' hook
// in the init block below. Kept as an injection seam -- the generator imposes no policy.
class CppTestDurationStatics : TestDurationStatics {
    init {
        // INIT SEAM: ensure the native library is loaded/initialized here (app-injected),
        // e.g. AudioCoreLib.load(). Left unspecified so no init policy is baked into codegen.
    }

    override fun hoursString(dt: java.time.Duration): String = hoursString_native(dt)
    private external fun hoursString_native(dt: java.time.Duration): String

    override fun minutesString(dt: java.time.Duration): String = minutesString_native(dt)
    private external fun minutesString_native(dt: java.time.Duration): String

    override fun secondsString(dt: java.time.Duration): String = secondsString_native(dt)
    private external fun secondsString_native(dt: java.time.Duration): String

    override fun millisString(dt: java.time.Duration): String = millisString_native(dt)
    private external fun millisString_native(dt: java.time.Duration): String

    override fun microsString(dt: java.time.Duration): String = microsString_native(dt)
    private external fun microsString_native(dt: java.time.Duration): String

    override fun nanosString(dt: java.time.Duration): String = nanosString_native(dt)
    private external fun nanosString_native(dt: java.time.Duration): String

    override fun hours(count: Int): java.time.Duration = hours_native(count)
    private external fun hours_native(count: Int): java.time.Duration

    override fun minutes(count: Int): java.time.Duration = minutes_native(count)
    private external fun minutes_native(count: Int): java.time.Duration

    override fun seconds(count: Int): java.time.Duration = seconds_native(count)
    private external fun seconds_native(count: Int): java.time.Duration

    override fun millis(count: Int): java.time.Duration = millis_native(count)
    private external fun millis_native(count: Int): java.time.Duration

    override fun micros(count: Int): java.time.Duration = micros_native(count)
    private external fun micros_native(count: Int): java.time.Duration

    override fun nanos(count: Int): java.time.Duration = nanos_native(count)
    private external fun nanos_native(count: Int): java.time.Duration

    override fun hoursf(count: Double): java.time.Duration = hoursf_native(count)
    private external fun hoursf_native(count: Double): java.time.Duration

    override fun minutesf(count: Double): java.time.Duration = minutesf_native(count)
    private external fun minutesf_native(count: Double): java.time.Duration

    override fun secondsf(count: Double): java.time.Duration = secondsf_native(count)
    private external fun secondsf_native(count: Double): java.time.Duration

    override fun millisf(count: Double): java.time.Duration = millisf_native(count)
    private external fun millisf_native(count: Double): java.time.Duration

    override fun microsf(count: Double): java.time.Duration = microsf_native(count)
    private external fun microsf_native(count: Double): java.time.Duration

    override fun nanosf(count: Double): java.time.Duration = nanosf_native(count)
    private external fun nanosf_native(count: Double): java.time.Duration

    override fun box(count: Long): java.time.Duration? = box_native(count)
    private external fun box_native(count: Long): java.time.Duration?

    override fun unbox(dt: java.time.Duration?): Long = unbox_native(dt)
    private external fun unbox_native(dt: java.time.Duration?): Long
}
