// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test

// Internal singleton for the TestArray static surface -- never visible to consumers. Reached only
// via the Companion hatch (legacy) + AudioCoreProviders. Stateless facade over the native
// statics; readiness gating lives at those seams (AudioCoreInit), not here.
internal object CppTestArrayStatics : TestArray {

    override fun testStringArray(a: Array<String>): Array<String> = testStringArray_native(a)
    private external fun testStringArray_native(a: Array<String>): Array<String>

    override fun testIntArray(a: IntArray): IntArray = testIntArray_native(a)
    private external fun testIntArray_native(a: IntArray): IntArray

    override fun testRecordArray(a: Array<Vec2>): Array<Vec2> = testRecordArray_native(a)
    private external fun testRecordArray_native(a: Array<Vec2>): Array<Vec2>

    override fun testArrayOfArray(a: Array<IntArray>): Array<IntArray> = testArrayOfArray_native(a)
    private external fun testArrayOfArray_native(a: Array<IntArray>): Array<IntArray>
}
