// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test

// Impl of TestArrayStatics. Constructing this is the SINGLE place the native surface becomes
// reachable, so it is the natural init gate: put your 'ensure .so loaded + initialized' hook
// in the init block below. Kept as an injection seam -- the generator imposes no policy.
class CppTestArrayStatics : TestArrayStatics {
    init {
        // INIT SEAM: ensure the native library is loaded/initialized here (app-injected),
        // e.g. AudioCoreLib.load(). Left unspecified so no init policy is baked into codegen.
    }

    override fun testStringArray(a: Array<String>): Array<String> = testStringArray_native(a)
    private external fun testStringArray_native(a: Array<String>): Array<String>

    override fun testIntArray(a: IntArray): IntArray = testIntArray_native(a)
    private external fun testIntArray_native(a: IntArray): IntArray

    override fun testRecordArray(a: Array<Vec2>): Array<Vec2> = testRecordArray_native(a)
    private external fun testRecordArray_native(a: Array<Vec2>): Array<Vec2>

    override fun testArrayOfArray(a: Array<IntArray>): Array<IntArray> = testArrayOfArray_native(a)
    private external fun testArrayOfArray_native(a: Array<IntArray>): Array<IntArray>
}
