// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test

// Internal singleton for the TestHelpers static surface -- never visible to consumers. Reached only
// via the Companion hatch (legacy) + AudioCoreProviders. Stateless facade over the native
// statics; readiness gating lives at those seams (AudioCoreInit), not here.
internal object CppTestHelpersStatics : TestHelpers {

    /** Method with documentation */
    override fun getSetRecord(): SetRecord = getSetRecord_native()
    private external fun getSetRecord_native(): SetRecord

    /**
     * Method with long documentation
     * (Second line of multi-line documentation.
     *   Indented third line of multi-line documentation.)
     */
    override fun checkSetRecord(rec: SetRecord): Boolean = checkSetRecord_native(rec)
    private external fun checkSetRecord_native(rec: SetRecord): Boolean

    override fun getPrimitiveList(): PrimitiveList = getPrimitiveList_native()
    private external fun getPrimitiveList_native(): PrimitiveList

    override fun checkPrimitiveList(pl: PrimitiveList): Boolean = checkPrimitiveList_native(pl)
    private external fun checkPrimitiveList_native(pl: PrimitiveList): Boolean

    override fun getNestedCollection(): NestedCollection = getNestedCollection_native()
    private external fun getNestedCollection_native(): NestedCollection

    override fun checkNestedCollection(nc: NestedCollection): Boolean = checkNestedCollection_native(nc)
    private external fun checkNestedCollection_native(nc: NestedCollection): Boolean

    override fun getMap(): Map<String, Long> = getMap_native()
    private external fun getMap_native(): Map<String, Long>

    override fun checkMap(m: Map<String, Long>): Boolean = checkMap_native(m)
    private external fun checkMap_native(m: Map<String, Long>): Boolean

    override fun getEmptyMap(): Map<String, Long> = getEmptyMap_native()
    private external fun getEmptyMap_native(): Map<String, Long>

    override fun checkEmptyMap(m: Map<String, Long>): Boolean = checkEmptyMap_native(m)
    private external fun checkEmptyMap_native(m: Map<String, Long>): Boolean

    override fun getMapListRecord(): MapListRecord = getMapListRecord_native()
    private external fun getMapListRecord_native(): MapListRecord

    override fun checkMapListRecord(m: MapListRecord): Boolean = checkMapListRecord_native(m)
    private external fun checkMapListRecord_native(m: MapListRecord): Boolean

    override fun checkClientInterfaceAscii(i: ClientInterface?) {
        checkClientInterfaceAscii_native(i)
    }
    private external fun checkClientInterfaceAscii_native(i: ClientInterface?)

    override fun checkClientInterfaceNonascii(i: ClientInterface?) {
        checkClientInterfaceNonascii_native(i)
    }
    private external fun checkClientInterfaceNonascii_native(i: ClientInterface?)

    override fun checkClientInterfaceArgs(i: ClientInterface?) {
        checkClientInterfaceArgs_native(i)
    }
    private external fun checkClientInterfaceArgs_native(i: ClientInterface?)

    override fun checkEnumMap(m: Map<Color, String>) {
        checkEnumMap_native(m)
    }
    private external fun checkEnumMap_native(m: Map<Color, String>)

    override fun checkEnum(c: Color) {
        checkEnum_native(c)
    }
    private external fun checkEnum_native(c: Color)

    override fun tokenId(t: UserToken?): UserToken? = tokenId_native(t)
    private external fun tokenId_native(t: UserToken?): UserToken?

    override fun createCppToken(): UserToken? = createCppToken_native()
    private external fun createCppToken_native(): UserToken?

    override fun checkCppToken(t: UserToken?) {
        checkCppToken_native(t)
    }
    private external fun checkCppToken_native(t: UserToken?)

    override fun cppTokenId(t: UserToken?): Long = cppTokenId_native(t)
    private external fun cppTokenId_native(t: UserToken?): Long

    override fun checkTokenType(t: UserToken?, type: String) {
        checkTokenType_native(t, type)
    }
    private external fun checkTokenType_native(t: UserToken?, type: String)

    override fun returnNone(): Int? = returnNone_native()
    private external fun returnNone_native(): Int?

    /** Ensures that we generate integer translation code */
    override fun assortedPrimitivesId(i: AssortedPrimitives): AssortedPrimitives = assortedPrimitivesId_native(i)
    private external fun assortedPrimitivesId_native(i: AssortedPrimitives): AssortedPrimitives

    override fun idBinary(b: ByteArray): ByteArray = idBinary_native(b)
    private external fun idBinary_native(b: ByteArray): ByteArray

    override fun getAsyncResult(): com.snapchat.djinni.Future<Int> = getAsyncResult_native()
    private external fun getAsyncResult_native(): com.snapchat.djinni.Future<Int>

    override fun futureRoundtrip(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String> = futureRoundtrip_native(f)
    private external fun futureRoundtrip_native(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String>

    override fun asyncEarlyThrow(): com.snapchat.djinni.Future<Int> = asyncEarlyThrow_native()
    private external fun asyncEarlyThrow_native(): com.snapchat.djinni.Future<Int>

    override fun voidAsyncMethod(f: com.snapchat.djinni.Future<Unit>): com.snapchat.djinni.Future<Unit> = voidAsyncMethod_native(f)
    private external fun voidAsyncMethod_native(f: com.snapchat.djinni.Future<Unit>): com.snapchat.djinni.Future<Unit>

    /**
     * If the input is empty, returns back an empty future.
     * If the input is non-empty, returns back the value plus one.
     */
    override fun addOneIfPresent(f: com.snapchat.djinni.Future<Int?>): com.snapchat.djinni.Future<Int?> = addOneIfPresent_native(f)
    private external fun addOneIfPresent_native(f: com.snapchat.djinni.Future<Int?>): com.snapchat.djinni.Future<Int?>

    /** try-catches the future f, and accesses the error message, and returns as a string. */
    override fun returnExceptionString(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String> = returnExceptionString_native(f)
    private external fun returnExceptionString_native(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String>

    override fun checkAsyncInterface(i: AsyncInterface?): com.snapchat.djinni.Future<String> = checkAsyncInterface_native(i)
    private external fun checkAsyncInterface_native(i: AsyncInterface?): com.snapchat.djinni.Future<String>

    override fun checkAsyncComposition(i: AsyncInterface?): com.snapchat.djinni.Future<String> = checkAsyncComposition_native(i)
    private external fun checkAsyncComposition_native(i: AsyncInterface?): com.snapchat.djinni.Future<String>

    override fun getOptionalList(): List<String?> = getOptionalList_native()
    private external fun getOptionalList_native(): List<String?>

    override fun checkOptionalList(ol: List<String?>): Boolean = checkOptionalList_native(ol)
    private external fun checkOptionalList_native(ol: List<String?>): Boolean

    override fun getOptionalSet(): Set<String?> = getOptionalSet_native()
    private external fun getOptionalSet_native(): Set<String?>

    override fun checkOptionalSet(os: Set<String?>): Boolean = checkOptionalSet_native(os)
    private external fun checkOptionalSet_native(os: Set<String?>): Boolean

    override fun getOptionalMap(): Map<String?, String?> = getOptionalMap_native()
    private external fun getOptionalMap_native(): Map<String?, String?>

    override fun checkOptionalMap(om: Map<String?, String?>): Boolean = checkOptionalMap_native(om)
    private external fun checkOptionalMap_native(om: Map<String?, String?>): Boolean
}
