// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from user_token.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

// CppProxy for UserToken -- wraps a native C++ implementation. Instance methods only;
// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members
// the JNI layer / support-lib bind to. Static factories live on CppUserTokenStatics.
class CppUserToken private constructor(private val nativeRef: Long) : UserToken {
    private val destroyed = AtomicBoolean(false)

    init {
        if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
        NativeObjectManager.register(this, nativeRef)
    }

    override fun whoami(): String {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_whoami(nativeRef)
    }
    private external fun native_whoami(_nativeRef: Long): String

    companion object {
        @JvmStatic
        external fun nativeDestroy(nativeRef: Long)
    }
}
