// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from single_language_interfaces.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

// CppProxy for UsesSingleLanguageListeners -- wraps a native C++ implementation. Instance methods only;
// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members
// the JNI layer / support-lib bind to. Static factories live on CppUsesSingleLanguageListenersStatics.
internal class CppUsesSingleLanguageListeners private constructor(private val nativeRef: Long) : UsesSingleLanguageListeners {
    private val destroyed = AtomicBoolean(false)

    init {
        if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
        NativeObjectManager.register(this, nativeRef)
    }

    override fun callForObjC(l: ObjcOnlyListener?) {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        native_callForObjC(nativeRef, l)
    }
    private external fun native_callForObjC(_nativeRef: Long, l: ObjcOnlyListener?)

    override fun returnForObjC(): ObjcOnlyListener? {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_returnForObjC(nativeRef)
    }
    private external fun native_returnForObjC(_nativeRef: Long): ObjcOnlyListener?

    override fun callForJava(l: JavaOnlyListener?) {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        native_callForJava(nativeRef, l)
    }
    private external fun native_callForJava(_nativeRef: Long, l: JavaOnlyListener?)

    override fun returnForJava(): JavaOnlyListener? {
        assert(!destroyed.get()) { "trying to use a destroyed object" }
        return native_returnForJava(nativeRef)
    }
    private external fun native_returnForJava(_nativeRef: Long): JavaOnlyListener?

    companion object {
        @JvmStatic
        external fun nativeDestroy(nativeRef: Long)
    }
}
