// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from data_ref_view.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `DataRefTest.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppDataRefTestStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: DataRefTestStatics by lazy(LazyThreadSafetyMode.NONE) { CppDataRefTestStatics() }

fun DataRefTest.Companion.create(): DataRefTest = instance.create()
