// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `FlagRoundtrip.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppFlagRoundtripStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: FlagRoundtripStatics by lazy(LazyThreadSafetyMode.NONE) { CppFlagRoundtripStatics() }

fun FlagRoundtrip.Companion.roundtripAccess(flag: java.util.EnumSet<AccessFlags>): java.util.EnumSet<AccessFlags> = instance.roundtripAccess(flag)

fun FlagRoundtrip.Companion.roundtripEmpty(flag: java.util.EnumSet<EmptyFlags>): java.util.EnumSet<EmptyFlags> = instance.roundtripEmpty(flag)

fun FlagRoundtrip.Companion.roundtripAccessBoxed(flag: java.util.EnumSet<AccessFlags>?): java.util.EnumSet<AccessFlags>? = instance.roundtripAccessBoxed(flag)

fun FlagRoundtrip.Companion.roundtripEmptyBoxed(flag: java.util.EnumSet<EmptyFlags>?): java.util.EnumSet<EmptyFlags>? = instance.roundtripEmptyBoxed(flag)
