// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `ListenerCaller.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppListenerCallerStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: ListenerCallerStatics by lazy(LazyThreadSafetyMode.NONE) { CppListenerCallerStatics() }

fun ListenerCaller.Companion.init(firstL: FirstListener?, secondL: SecondListener?): ListenerCaller = instance.init(firstL, secondL)
