// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test

import kotlinx.coroutines.runBlocking

// Source-compat hatch: old `ListenerCaller.<static>(...)` call sites keep compiling -- now init-SAFE.
// Each hatch blocks on AudioCore readiness before touching the native surface, so a pre-init
// call WAITS instead of crashing (old code pays with a blocked thread; new code should migrate
// to the suspend AudioCoreProviders). Delegates to the internal CppListenerCallerStatics singleton (also reused
// by AudioCoreProvidersImpl).

fun ListenerCaller.Companion.init(firstL: FirstListener?, secondL: SecondListener?): ListenerCaller? {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppListenerCallerStatics.init(firstL, secondL)
}
