// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `ProtoTests.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppProtoTestsStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: ProtoTestsStatics by lazy(LazyThreadSafetyMode.NONE) { CppProtoTestsStatics() }

fun ProtoTests.Companion.protoToStrings(x: AddressBook): List<String> = instance.protoToStrings(x)

fun ProtoTests.Companion.stringsToProto(x: List<String>): AddressBook = instance.stringsToProto(x)

fun ProtoTests.Companion.embeddedProtoToString(x: RecordWithEmbeddedProto): String = instance.embeddedProtoToString(x)

fun ProtoTests.Companion.stringToEmbeddedProto(x: String): RecordWithEmbeddedProto = instance.stringToEmbeddedProto(x)

fun ProtoTests.Companion.cppProtoToString(x: PersistingState): String = instance.cppProtoToString(x)

fun ProtoTests.Companion.stringToCppProto(x: String): PersistingState = instance.stringToCppProto(x)

fun ProtoTests.Companion.embeddedCppProtoToString(x: RecordWithEmbeddedCppProto): String = instance.embeddedCppProtoToString(x)

fun ProtoTests.Companion.stringToEmbeddedCppProto(x: String): RecordWithEmbeddedCppProto = instance.stringToEmbeddedCppProto(x)

fun ProtoTests.Companion.protoListToStrings(x: List<Person>): List<String> = instance.protoListToStrings(x)

fun ProtoTests.Companion.stringsToProtoList(x: List<String>): List<Person> = instance.stringsToProtoList(x)

fun ProtoTests.Companion.optionalProtoToString(x: Person?): String = instance.optionalProtoToString(x)

fun ProtoTests.Companion.stringToOptionalProto(x: String): Person? = instance.stringToOptionalProto(x)

fun ProtoTests.Companion.stringToProtoOutcome(x: String): com.snapchat.djinni.Outcome<Person, Int> = instance.stringToProtoOutcome(x)
