// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `ReturnOne.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppReturnOneStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: ReturnOneStatics by lazy(LazyThreadSafetyMode.NONE) { CppReturnOneStatics() }

fun ReturnOne.Companion.getInstance(): ReturnOne = instance.getInstance()
