// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `ReturnTwo.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppReturnTwoStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: ReturnTwoStatics by lazy(LazyThreadSafetyMode.NONE) { CppReturnTwoStatics() }

fun ReturnTwo.Companion.getInstance(): ReturnTwo = instance.getInstance()
