// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `ReverseClientInterface.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppReverseClientInterfaceStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: ReverseClientInterfaceStatics by lazy(LazyThreadSafetyMode.NONE) { CppReverseClientInterfaceStatics() }

fun ReverseClientInterface.Companion.create(): ReverseClientInterface = instance.create()
