// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `TestOutcome.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppTestOutcomeStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: TestOutcomeStatics by lazy(LazyThreadSafetyMode.NONE) { CppTestOutcomeStatics() }

fun TestOutcome.Companion.getSuccessOutcome(): com.snapchat.djinni.Outcome<String, Int> = instance.getSuccessOutcome()

fun TestOutcome.Companion.getErrorOutcome(): com.snapchat.djinni.Outcome<String, Int> = instance.getErrorOutcome()

fun TestOutcome.Companion.putSuccessOutcome(x: com.snapchat.djinni.Outcome<String, Int>): String = instance.putSuccessOutcome(x)

fun TestOutcome.Companion.putErrorOutcome(x: com.snapchat.djinni.Outcome<String, Int>): Int = instance.putErrorOutcome(x)

fun TestOutcome.Companion.getNestedSuccessOutcome(): NestedOutcome = instance.getNestedSuccessOutcome()

fun TestOutcome.Companion.getNestedErrorOutcome(): NestedOutcome = instance.getNestedErrorOutcome()

fun TestOutcome.Companion.putNestedSuccessOutcome(x: NestedOutcome): Int = instance.putNestedSuccessOutcome(x)

fun TestOutcome.Companion.putNestedErrorOutcome(x: NestedOutcome): String = instance.putNestedErrorOutcome(x)
