// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `TestArray.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppTestArrayStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: TestArrayStatics by lazy(LazyThreadSafetyMode.NONE) { CppTestArrayStatics() }

fun TestArray.Companion.testStringArray(a: Array<String>): Array<String> = instance.testStringArray(a)

fun TestArray.Companion.testIntArray(a: IntArray): IntArray = instance.testIntArray(a)

fun TestArray.Companion.testRecordArray(a: Array<Vec2>): Array<Vec2> = instance.testRecordArray(a)

fun TestArray.Companion.testArrayOfArray(a: Array<IntArray>): Array<IntArray> = instance.testArrayOfArray(a)
