// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `TestDuration.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppTestDurationStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: TestDurationStatics by lazy(LazyThreadSafetyMode.NONE) { CppTestDurationStatics() }

fun TestDuration.Companion.hoursString(dt: java.time.Duration): String = instance.hoursString(dt)

fun TestDuration.Companion.minutesString(dt: java.time.Duration): String = instance.minutesString(dt)

fun TestDuration.Companion.secondsString(dt: java.time.Duration): String = instance.secondsString(dt)

fun TestDuration.Companion.millisString(dt: java.time.Duration): String = instance.millisString(dt)

fun TestDuration.Companion.microsString(dt: java.time.Duration): String = instance.microsString(dt)

fun TestDuration.Companion.nanosString(dt: java.time.Duration): String = instance.nanosString(dt)

fun TestDuration.Companion.hours(count: Int): java.time.Duration = instance.hours(count)

fun TestDuration.Companion.minutes(count: Int): java.time.Duration = instance.minutes(count)

fun TestDuration.Companion.seconds(count: Int): java.time.Duration = instance.seconds(count)

fun TestDuration.Companion.millis(count: Int): java.time.Duration = instance.millis(count)

fun TestDuration.Companion.micros(count: Int): java.time.Duration = instance.micros(count)

fun TestDuration.Companion.nanos(count: Int): java.time.Duration = instance.nanos(count)

fun TestDuration.Companion.hoursf(count: Double): java.time.Duration = instance.hoursf(count)

fun TestDuration.Companion.minutesf(count: Double): java.time.Duration = instance.minutesf(count)

fun TestDuration.Companion.secondsf(count: Double): java.time.Duration = instance.secondsf(count)

fun TestDuration.Companion.millisf(count: Double): java.time.Duration = instance.millisf(count)

fun TestDuration.Companion.microsf(count: Double): java.time.Duration = instance.microsf(count)

fun TestDuration.Companion.nanosf(count: Double): java.time.Duration = instance.nanosf(count)

fun TestDuration.Companion.box(count: Long): java.time.Duration? = instance.box(count)

fun TestDuration.Companion.unbox(dt: java.time.Duration?): Long = instance.unbox(dt)
