// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test

import kotlinx.coroutines.runBlocking

// Source-compat hatch: old `TestArray.<static>(...)` call sites keep compiling -- now init-SAFE.
// Each hatch blocks on AudioCore readiness before touching the native surface, so a pre-init
// call WAITS instead of crashing (old code pays with a blocked thread; new code should migrate
// to the suspend AudioCoreProviders). Delegates to the internal CppTestArrayStatics singleton (also reused
// by AudioCoreProvidersImpl).

fun TestArray.Companion.testStringArray(a: Array<String>): Array<String> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestArrayStatics.testStringArray(a)
}

fun TestArray.Companion.testIntArray(a: IntArray): IntArray {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestArrayStatics.testIntArray(a)
}

fun TestArray.Companion.testRecordArray(a: Array<Vec2>): Array<Vec2> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestArrayStatics.testRecordArray(a)
}

fun TestArray.Companion.testArrayOfArray(a: Array<IntArray>): Array<IntArray> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestArrayStatics.testArrayOfArray(a)
}
