// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test

import kotlinx.coroutines.runBlocking

// Source-compat hatch: old `TestDuration.<static>(...)` call sites keep compiling -- now init-SAFE.
// Each hatch blocks on AudioCore readiness before touching the native surface, so a pre-init
// call WAITS instead of crashing (old code pays with a blocked thread; new code should migrate
// to the suspend AudioCoreProviders). Delegates to the internal CppTestDurationStatics singleton (also reused
// by AudioCoreProvidersImpl).

fun TestDuration.Companion.hoursString(dt: java.time.Duration): String {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.hoursString(dt)
}

fun TestDuration.Companion.minutesString(dt: java.time.Duration): String {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.minutesString(dt)
}

fun TestDuration.Companion.secondsString(dt: java.time.Duration): String {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.secondsString(dt)
}

fun TestDuration.Companion.millisString(dt: java.time.Duration): String {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.millisString(dt)
}

fun TestDuration.Companion.microsString(dt: java.time.Duration): String {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.microsString(dt)
}

fun TestDuration.Companion.nanosString(dt: java.time.Duration): String {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.nanosString(dt)
}

fun TestDuration.Companion.hours(count: Int): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.hours(count)
}

fun TestDuration.Companion.minutes(count: Int): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.minutes(count)
}

fun TestDuration.Companion.seconds(count: Int): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.seconds(count)
}

fun TestDuration.Companion.millis(count: Int): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.millis(count)
}

fun TestDuration.Companion.micros(count: Int): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.micros(count)
}

fun TestDuration.Companion.nanos(count: Int): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.nanos(count)
}

fun TestDuration.Companion.hoursf(count: Double): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.hoursf(count)
}

fun TestDuration.Companion.minutesf(count: Double): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.minutesf(count)
}

fun TestDuration.Companion.secondsf(count: Double): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.secondsf(count)
}

fun TestDuration.Companion.millisf(count: Double): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.millisf(count)
}

fun TestDuration.Companion.microsf(count: Double): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.microsf(count)
}

fun TestDuration.Companion.nanosf(count: Double): java.time.Duration {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.nanosf(count)
}

fun TestDuration.Companion.box(count: Long): java.time.Duration? {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.box(count)
}

fun TestDuration.Companion.unbox(dt: java.time.Duration?): Long {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestDurationStatics.unbox(dt)
}
