// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test

import kotlinx.coroutines.runBlocking

// Source-compat hatch: old `TestHelpers.<static>(...)` call sites keep compiling -- now init-SAFE.
// Each hatch blocks on AudioCore readiness before touching the native surface, so a pre-init
// call WAITS instead of crashing (old code pays with a blocked thread; new code should migrate
// to the suspend AudioCoreProviders). Delegates to the internal CppTestHelpersStatics singleton (also reused
// by AudioCoreProvidersImpl).

fun TestHelpers.Companion.getSetRecord(): SetRecord {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.getSetRecord()
}

fun TestHelpers.Companion.checkSetRecord(rec: SetRecord): Boolean {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.checkSetRecord(rec)
}

fun TestHelpers.Companion.getPrimitiveList(): PrimitiveList {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.getPrimitiveList()
}

fun TestHelpers.Companion.checkPrimitiveList(pl: PrimitiveList): Boolean {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.checkPrimitiveList(pl)
}

fun TestHelpers.Companion.getNestedCollection(): NestedCollection {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.getNestedCollection()
}

fun TestHelpers.Companion.checkNestedCollection(nc: NestedCollection): Boolean {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.checkNestedCollection(nc)
}

fun TestHelpers.Companion.getMap(): Map<String, Long> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.getMap()
}

fun TestHelpers.Companion.checkMap(m: Map<String, Long>): Boolean {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.checkMap(m)
}

fun TestHelpers.Companion.getEmptyMap(): Map<String, Long> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.getEmptyMap()
}

fun TestHelpers.Companion.checkEmptyMap(m: Map<String, Long>): Boolean {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.checkEmptyMap(m)
}

fun TestHelpers.Companion.getMapListRecord(): MapListRecord {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.getMapListRecord()
}

fun TestHelpers.Companion.checkMapListRecord(m: MapListRecord): Boolean {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.checkMapListRecord(m)
}

fun TestHelpers.Companion.checkClientInterfaceAscii(i: ClientInterface?) {
    runBlocking { AudioCoreInit.awaitReady() }
    CppTestHelpersStatics.checkClientInterfaceAscii(i)
}

fun TestHelpers.Companion.checkClientInterfaceNonascii(i: ClientInterface?) {
    runBlocking { AudioCoreInit.awaitReady() }
    CppTestHelpersStatics.checkClientInterfaceNonascii(i)
}

fun TestHelpers.Companion.checkClientInterfaceArgs(i: ClientInterface?) {
    runBlocking { AudioCoreInit.awaitReady() }
    CppTestHelpersStatics.checkClientInterfaceArgs(i)
}

fun TestHelpers.Companion.checkEnumMap(m: Map<Color, String>) {
    runBlocking { AudioCoreInit.awaitReady() }
    CppTestHelpersStatics.checkEnumMap(m)
}

fun TestHelpers.Companion.checkEnum(c: Color) {
    runBlocking { AudioCoreInit.awaitReady() }
    CppTestHelpersStatics.checkEnum(c)
}

fun TestHelpers.Companion.tokenId(t: UserToken?): UserToken? {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.tokenId(t)
}

fun TestHelpers.Companion.createCppToken(): UserToken? {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.createCppToken()
}

fun TestHelpers.Companion.checkCppToken(t: UserToken?) {
    runBlocking { AudioCoreInit.awaitReady() }
    CppTestHelpersStatics.checkCppToken(t)
}

fun TestHelpers.Companion.cppTokenId(t: UserToken?): Long {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.cppTokenId(t)
}

fun TestHelpers.Companion.checkTokenType(t: UserToken?, type: String) {
    runBlocking { AudioCoreInit.awaitReady() }
    CppTestHelpersStatics.checkTokenType(t, type)
}

fun TestHelpers.Companion.returnNone(): Int? {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.returnNone()
}

fun TestHelpers.Companion.assortedPrimitivesId(i: AssortedPrimitives): AssortedPrimitives {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.assortedPrimitivesId(i)
}

fun TestHelpers.Companion.idBinary(b: ByteArray): ByteArray {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.idBinary(b)
}

fun TestHelpers.Companion.getAsyncResult(): com.snapchat.djinni.Future<Int> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.getAsyncResult()
}

fun TestHelpers.Companion.futureRoundtrip(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.futureRoundtrip(f)
}

fun TestHelpers.Companion.asyncEarlyThrow(): com.snapchat.djinni.Future<Int> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.asyncEarlyThrow()
}

fun TestHelpers.Companion.voidAsyncMethod(f: com.snapchat.djinni.Future<Unit>): com.snapchat.djinni.Future<Unit> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.voidAsyncMethod(f)
}

fun TestHelpers.Companion.addOneIfPresent(f: com.snapchat.djinni.Future<Int?>): com.snapchat.djinni.Future<Int?> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.addOneIfPresent(f)
}

fun TestHelpers.Companion.returnExceptionString(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.returnExceptionString(f)
}

fun TestHelpers.Companion.checkAsyncInterface(i: AsyncInterface?): com.snapchat.djinni.Future<String> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.checkAsyncInterface(i)
}

fun TestHelpers.Companion.checkAsyncComposition(i: AsyncInterface?): com.snapchat.djinni.Future<String> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.checkAsyncComposition(i)
}

fun TestHelpers.Companion.getOptionalList(): List<String?> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.getOptionalList()
}

fun TestHelpers.Companion.checkOptionalList(ol: List<String?>): Boolean {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.checkOptionalList(ol)
}

fun TestHelpers.Companion.getOptionalSet(): Set<String?> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.getOptionalSet()
}

fun TestHelpers.Companion.checkOptionalSet(os: Set<String?>): Boolean {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.checkOptionalSet(os)
}

fun TestHelpers.Companion.getOptionalMap(): Map<String?, String?> {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.getOptionalMap()
}

fun TestHelpers.Companion.checkOptionalMap(om: Map<String?, String?>): Boolean {
    runBlocking { AudioCoreInit.awaitReady() }
    return CppTestHelpersStatics.checkOptionalMap(om)
}
