// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test

// Source-compat extensions: old `TestHelpers.<static>(...)` call sites keep compiling (Kotlin; needs
// the import). Backed by one lazy(NONE) CppTestHelpersStatics -- no synchronized check on hot static calls;
// idempotent init + stateless delegator, so a first-call race is harmless.
private val instance: TestHelpersStatics by lazy(LazyThreadSafetyMode.NONE) { CppTestHelpersStatics() }

fun TestHelpers.Companion.getSetRecord(): SetRecord = instance.getSetRecord()

fun TestHelpers.Companion.checkSetRecord(rec: SetRecord): Boolean = instance.checkSetRecord(rec)

fun TestHelpers.Companion.getPrimitiveList(): PrimitiveList = instance.getPrimitiveList()

fun TestHelpers.Companion.checkPrimitiveList(pl: PrimitiveList): Boolean = instance.checkPrimitiveList(pl)

fun TestHelpers.Companion.getNestedCollection(): NestedCollection = instance.getNestedCollection()

fun TestHelpers.Companion.checkNestedCollection(nc: NestedCollection): Boolean = instance.checkNestedCollection(nc)

fun TestHelpers.Companion.getMap(): Map<String, Long> = instance.getMap()

fun TestHelpers.Companion.checkMap(m: Map<String, Long>): Boolean = instance.checkMap(m)

fun TestHelpers.Companion.getEmptyMap(): Map<String, Long> = instance.getEmptyMap()

fun TestHelpers.Companion.checkEmptyMap(m: Map<String, Long>): Boolean = instance.checkEmptyMap(m)

fun TestHelpers.Companion.getMapListRecord(): MapListRecord = instance.getMapListRecord()

fun TestHelpers.Companion.checkMapListRecord(m: MapListRecord): Boolean = instance.checkMapListRecord(m)

fun TestHelpers.Companion.checkClientInterfaceAscii(i: ClientInterface?) = instance.checkClientInterfaceAscii(i)

fun TestHelpers.Companion.checkClientInterfaceNonascii(i: ClientInterface?) = instance.checkClientInterfaceNonascii(i)

fun TestHelpers.Companion.checkClientInterfaceArgs(i: ClientInterface?) = instance.checkClientInterfaceArgs(i)

fun TestHelpers.Companion.checkEnumMap(m: Map<Color, String>) = instance.checkEnumMap(m)

fun TestHelpers.Companion.checkEnum(c: Color) = instance.checkEnum(c)

fun TestHelpers.Companion.tokenId(t: UserToken?): UserToken? = instance.tokenId(t)

fun TestHelpers.Companion.createCppToken(): UserToken = instance.createCppToken()

fun TestHelpers.Companion.checkCppToken(t: UserToken?) = instance.checkCppToken(t)

fun TestHelpers.Companion.cppTokenId(t: UserToken?): Long = instance.cppTokenId(t)

fun TestHelpers.Companion.checkTokenType(t: UserToken?, type: String) = instance.checkTokenType(t, type)

fun TestHelpers.Companion.returnNone(): Int? = instance.returnNone()

fun TestHelpers.Companion.assortedPrimitivesId(i: AssortedPrimitives): AssortedPrimitives = instance.assortedPrimitivesId(i)

fun TestHelpers.Companion.idBinary(b: ByteArray): ByteArray = instance.idBinary(b)

fun TestHelpers.Companion.getAsyncResult(): com.snapchat.djinni.Future<Int> = instance.getAsyncResult()

fun TestHelpers.Companion.futureRoundtrip(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String> = instance.futureRoundtrip(f)

fun TestHelpers.Companion.asyncEarlyThrow(): com.snapchat.djinni.Future<Int> = instance.asyncEarlyThrow()

fun TestHelpers.Companion.voidAsyncMethod(f: com.snapchat.djinni.Future<Unit>): com.snapchat.djinni.Future<Unit> = instance.voidAsyncMethod(f)

fun TestHelpers.Companion.addOneIfPresent(f: com.snapchat.djinni.Future<Int?>): com.snapchat.djinni.Future<Int?> = instance.addOneIfPresent(f)

fun TestHelpers.Companion.returnExceptionString(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String> = instance.returnExceptionString(f)

fun TestHelpers.Companion.checkAsyncInterface(i: AsyncInterface?): com.snapchat.djinni.Future<String> = instance.checkAsyncInterface(i)

fun TestHelpers.Companion.checkAsyncComposition(i: AsyncInterface?): com.snapchat.djinni.Future<String> = instance.checkAsyncComposition(i)

fun TestHelpers.Companion.getOptionalList(): List<String?> = instance.getOptionalList()

fun TestHelpers.Companion.checkOptionalList(ol: List<String?>): Boolean = instance.checkOptionalList(ol)

fun TestHelpers.Companion.getOptionalSet(): Set<String?> = instance.getOptionalSet()

fun TestHelpers.Companion.checkOptionalSet(os: Set<String?>): Boolean = instance.checkOptionalSet(os)

fun TestHelpers.Companion.getOptionalMap(): Map<String?, String?> = instance.getOptionalMap()

fun TestHelpers.Companion.checkOptionalMap(om: Map<String?, String?>): Boolean = instance.checkOptionalMap(om)
