/**
  * Copyright 2014 Dropbox, Inc.
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  *
  *    http://www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an "AS IS" BASIS,
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
  *
  * Kotlin backend (PoC). Modeled on JavaGenerator. JavaGenerator/JavaMarshal are NOT modified.
  */

package djinni

import java.io.File

import djinni.ast.Record.DerivingType
import djinni.ast._
import djinni.generatorTools._
import djinni.meta._
import djinni.writer.IndentWriter

// Emits an idiomatic Kotlin surface alongside (never replacing) the Java backend.
//
// Layout -- the API/impl split, by construction:
//   <kotlin-out>/api/<Name>.kt         pure declarations: enum class / data class / interface.
//                                       No JNI, no `external`, no NativeObjectManager -> compiles in a
//                                       pure-JVM module with no native dependency.
//   <kotlin-out>/impl/<Name>CppProxy.kt the CppProxy: `external` native methods, nativeRef + destroyed
//                                       lifetime, NativeObjectManager registration. Depends on the API
//                                       + the support-lib only.
//
// JVM-name parity: type/field/method/enum names all come from the Java ident style (idJava), so the
// member surface matches today's generated Java and the existing JNI layer keeps binding. The
// intentional deltas are: idiomatic type shapes + nullability, the api/impl file split, and a non-null
// create(). See IMPLEMENTATION-NOTES.md for the exact JNI-side implications of the last two.
class KotlinGenerator(spec: Spec) extends Generator(spec) {

  val marshal = new KotlinMarshal(spec)

  private val apiFolder = new File(spec.kotlinOutFolder.get, "api")
  private val implFolder = new File(spec.kotlinOutFolder.get, "impl")

  private def writeKotlinFile(folder: File, fileName: String, origin: String, imports: Iterable[String], f: IndentWriter => Unit) {
    if (!spec.skipGeneration) {
      createFolder("Kotlin", folder)
    }
    createFile(folder, fileName, (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      spec.kotlinPackage.foreach(p => w.wl(s"package $p").wl)
      if (imports.nonEmpty) {
        imports.foreach(i => w.wl(s"import $i"))
        w.wl
      }
      f(w)
    })
  }

  private def kotlinTypeParams(params: Seq[TypeParam]): String =
    if (params.isEmpty) "" else params.map(p => idJava.typeParam(p.ident)).mkString("<", ", ", ">")

  // ": Type" for a return, or "" for void (idiomatic Kotlin omits `: Unit`).
  private def retSuffix(ret: Option[TypeRef]): String = ret.fold("")(t => ": " + marshal.returnType(Some(t)))

  // ==============================================================================================
  // Enum -> enum class (pure API). Standard JVM enum: values()/valueOf()/ordinal()/name() are
  // identical to a Java enum, so the JNI JniEnum helper binds unchanged.
  // ==============================================================================================
  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: Enum) {
    writeKotlinFile(apiFolder, idJava.ty(ident) + ".kt", origin, Nil, w => {
      writeDoc(w, doc)
      w.w(s"enum class ${marshal.typename(ident, e)}").braced {
        // Only "normal" options become constants; NoFlags/AllFlags are synthesized via EnumSet in
        // types, exactly as the Java backend does.
        for (o <- normalEnumOptions(e)) {
          writeDoc(w, o.doc)
          w.wl(idJava.enum(o.ident) + ",")
        }
      }
    })
  }

  // ==============================================================================================
  // Record -> data class (pure API). Fields use the idiomatic read-only collection flavor
  // (List/Set/Map, via KotlinMarshal.fieldType(concrete=false)) and boxed optionals (T?). This is
  // the team's idiomatic-surface decision: collections are read-only interfaces everywhere and only
  // arrays stay mutable. The JNI record marshalling then binds the collection *interface* descriptors
  // (Ljava/util/List; etc.) rather than concrete java.util.* -- a deferred JNI-side change tracked in
  // IMPLEMENTATION-NOTES, not a surface blocker.
  // ==============================================================================================
  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record) {
    // Mirror JavaGenerator's extended-record naming so the class name matches (ABI).
    val name = if (r.ext.java) ident.name + "_base" else ident.name
    val self = marshal.typename(name, r)
    val tpl = kotlinTypeParams(params)

    writeKotlinFile(apiFolder, idJava.ty(name) + ".kt", origin, Nil, w => {
      writeDoc(w, doc)

      val interfaces = scala.collection.mutable.ArrayBuffer[String]()
      if (r.derivingTypes.contains(DerivingType.Ord)) interfaces += s"Comparable<$self$tpl>"
      val impl = if (interfaces.isEmpty) "" else " : " + interfaces.mkString(", ")

      if (r.fields.isEmpty) {
        // Kotlin forbids a data class with no constructor params; emit a plain class (matches an
        // empty Java record's zero-arg constructor).
        w.w(s"class $self$tpl$impl").braced {
          generateRecordConsts(w, self, r.consts)
        }
      } else {
        w.wl(s"data class $self$tpl(")
        w.nested {
          for (f <- r.fields) {
            writeDoc(w, f.doc)
            w.wl(s"val ${idJava.field(f.ident)}: ${marshal.fieldType(f.ty)},")
          }
        }
        if (r.consts.nonEmpty || r.derivingTypes.contains(DerivingType.Ord)) {
          w.w(s")$impl").braced {
            if (r.derivingTypes.contains(DerivingType.Ord)) generateCompareTo(w, self + tpl, r)
            generateRecordConsts(w, self, r.consts)
          }
        } else {
          w.wl(s")$impl")
        }
      }
    })
  }

  // deriving(ord) -> Comparable<Self>.compareTo. Mirrors JavaGenerator's field-by-field ordering:
  // compare each field in declaration order, returning at the first non-equal field. Every field type
  // that reaches here is Comparable in Kotlin -- primitives (Byte/Short/Int/Long/Float/Double), String,
  // enums, java.util.Date / java.time.Duration externs, and nested ord records (whose generated
  // compareTo we recurse into) -- so a uniform `.compareTo` gives the natural order Java produces.
  private def generateCompareTo(w: IndentWriter, selfWithTpl: String, r: Record) {
    w.wl
    w.w(s"override fun compareTo(other: $selfWithTpl): Int").braced {
      w.wl("var tempResult: Int")
      for (f <- r.fields) {
        val name = idJava.field(f.ident)
        w.wl(s"tempResult = this.$name.compareTo(other.$name)")
        w.w("if (tempResult != 0)").braced {
          w.wl("return tempResult")
        }
      }
      w.wl("return 0")
    }
  }

  private def generateRecordConsts(w: IndentWriter, self: String, consts: Seq[Const]) {
    if (consts.isEmpty) return
    w.wl
    w.w("companion object").braced {
      writeKotlinConsts(w, consts)
    }
  }

  // ==============================================================================================
  // Interface -> `interface` (pure API) + a separate CppProxy (impl).
  // ==============================================================================================
  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface) {
    val statics = i.methods.filter(m => m.static && m.lang.java)
    generateInterfaceApi(origin, ident, doc, typeParams, i)
    // Statics become an INJECTABLE service (interface + impl) rather than language statics: hides the
    // native surface, makes them mockable, and gives one init chokepoint (the impl's construction).
    if (statics.nonEmpty) generateStaticsApi(origin, ident, doc, typeParams, i, statics)
    if (i.ext.cpp) {
      generateInterfaceCppProxy(origin, ident, doc, typeParams, i)
      if (statics.nonEmpty) {
        generateStaticsImpl(origin, ident, doc, typeParams, i, statics)
        generateStaticsCompatExtensions(origin, ident, doc, typeParams, i, statics)
      }
    }
  }

  // --- Property synthesis: getX()/isX()/setX() accessor methods on an interface become Kotlin
  // val/var properties, so callers write `obj.sampleRate` (matching data-class access + how the old
  // Java API read via Kotlin synthetic properties). The native_* methods are emitted UNCHANGED, so
  // the JNI binding is untouched -- only the public surface becomes a property. Conservative: only
  // no-arg get_*/is_* (getter), paired with a single-arg void set_* of matching type (-> var).
  // Detection works off the NORMALIZED Java method name (idJava.method), so BOTH snake_case IDL
  // (`get_foo`/`is_x`/`set_foo`) AND camelCase IDL (`getFoo`/`isX`/`setFoo`) are recognized as
  // accessors -- exactly matching how the old Java binding + Kotlin synthetic properties exposed
  // every such method as `obj.foo` / `obj.isX` (which is what the existing call sites use). The
  // charAt-after-prefix .isUpper guard excludes non-accessors like `setup()`/`island()`/`getaway()`.
  private def jName(m: Interface.Method): String = idJava.method(m.ident)
  private def isGetterName(jn: String): Boolean =
    (jn.length > 3 && jn.startsWith("get") && jn.charAt(3).isUpper) ||
    (jn.length > 2 && jn.startsWith("is")  && jn.charAt(2).isUpper)
  private def isSetterName(jn: String): Boolean =
    jn.length > 3 && jn.startsWith("set") && jn.charAt(3).isUpper
  private def isGetterM(m: Interface.Method): Boolean =
    !m.static && m.params.isEmpty && m.ret.isDefined && isGetterName(jName(m))
  private def isSetterM(m: Interface.Method): Boolean =
    !m.static && m.params.length == 1 && m.ret.isEmpty && isSetterName(jName(m))
  private def accBase(m: Interface.Method): String = {
    val jn = jName(m)
    if (jn.startsWith("get") || jn.startsWith("set")) jn.substring(3) else jn.substring(2)
  }
  private def propName(g: Interface.Method): String = {
    val jn = jName(g)
    if (jn.startsWith("get")) { val s = jn.substring(3); s.head.toLower.toString + s.tail } else jn
  }
  private def interfaceAccessors(i: Interface): (Seq[(Interface.Method, Option[Interface.Method])], Seq[Interface.Method]) = {
    val instance = i.methods.filter(m => !m.static)
    val setterByBase = instance.filter(isSetterM).map(s => accBase(s) -> s).toMap
    val props = instance.filter(isGetterM).map { g =>
      val s = setterByBase.get(accBase(g)).filter(st => marshal.paramType(st.params.head.ty) == marshal.returnType(g.ret))
      (g, s)
    }
    val consumed = props.flatMap { case (g, s) => g +: s.toSeq }.toSet
    (props, instance.filterNot(consumed.contains))
  }

  private def generateInterfaceApi(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface) {
    val self = marshal.typename(ident, i)
    val tpl = kotlinTypeParams(typeParams)

    writeKotlinFile(apiFolder, idJava.ty(ident) + ".kt", origin, Nil, w => {
      writeDoc(w, doc)
      w.w(s"interface $self$tpl").braced {
        // Accessor methods (get_/is_/set_) become val/var properties; everything else stays a fun.
        // Static factories do NOT live here -- they're on the injectable <Name>Statics.
        val (props, plain) = interfaceAccessors(i)
        for ((g, sOpt) <- props) {
          writeMethodDoc(w, g, idJava.local)
          w.wl(s"${if (sOpt.isDefined) "var" else "val"} ${propName(g)}: ${marshal.returnType(g.ret)}")
        }
        for (m <- plain) {
          writeMethodDoc(w, m, idJava.local)
          val params = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
          w.wl(s"fun ${idJava.method(m.ident)}($params)${retSuffix(m.ret)}")
        }

        // Constants stay on the API interface. Also emit an (otherwise empty) companion when the
        // interface has statics -- it's the anchor the @Deprecated source-compat extensions attach to,
        // keeping the old `<Name>.<static>(...)` call syntax compiling.
        val hasStatics = i.methods.exists(m => m.static && m.lang.java)
        if (i.consts.nonEmpty || hasStatics) {
          w.wl
          w.w("companion object").braced {
            writeKotlinConsts(w, i.consts)
          }
        }
      }
    })
  }

  // Statics-as-service. A djinni interface `static` (create, ...) is exposed NOT as a language static
  // but as an instance method on an injectable service:
  //   api:  interface <Name>Statics    { fun create(...): <Name>; ... }
  //   impl: class Cpp<Name>Statics : <Name>Statics { init { <inject init> }  ...private external... }
  // Call sites depend on the interface (mockable in tests). The `external` natives are private INSTANCE
  // members of the impl, reachable only via a Cpp<Name>Statics instance -- so constructing that
  // instance is the single init chokepoint.

  // ": T" for the statics service signature: factories (return this-interface) are non-null; other
  // statics keep the mirrored policy type; void -> "".
  private def staticReturnType(m: Interface.Method): String =
    if (m.ret.isEmpty) ""
    else if (m.ret.exists(t => isInterface(t.resolved))) ": " + marshal.returnTypeNonNull(m.ret)
    else retSuffix(m.ret)

  private def generateStaticsApi(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface, statics: Seq[Interface.Method]) {
    val self = marshal.typename(ident, i)
    writeKotlinFile(apiFolder, self + "Statics.kt", origin, Nil, w => {
      w.wl(s"// Injectable statics service for $self (replaces language-level statics).")
      w.wl(s"// Depend on THIS at call sites so the native surface stays hidden and mockable; a real")
      w.wl(s"// instance comes from Cpp${self}Statics (impl), whose construction is the init gate.")
      w.w(s"interface ${self}Statics").braced {
        for (m <- statics) {
          writeMethodDoc(w, m, idJava.local)
          val params = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
          w.wl(s"fun ${idJava.method(m.ident)}($params)${staticReturnType(m)}")
        }
      }
    })
  }

  private def generateStaticsImpl(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface, statics: Seq[Interface.Method]) {
    val self = marshal.typename(ident, i)
    val impl = "Cpp" + self + "Statics"
    writeKotlinFile(implFolder, impl + ".kt", origin, Nil, w => {
      w.wl(s"// Impl of ${self}Statics. Constructing this is the SINGLE place the native surface becomes")
      w.wl(s"// reachable, so it is the natural init gate: put your 'ensure .so loaded + initialized' hook")
      w.wl(s"// in the init block below. Kept as an injection seam -- the generator imposes no policy.")
      w.w(s"class $impl : ${self}Statics").braced {
        w.w("init").braced {
          w.wl("// INIT SEAM: ensure the native library is loaded/initialized here (app-injected),")
          w.wl("// e.g. AudioCoreLib.load(). Left unspecified so no init policy is baked into codegen.")
        }
        for (m <- statics) {
          writeStaticsMember(w, ident, m)
        }
      }
    })
  }

  // One statics member: a public `override` wrapper (non-null + throw for factories) over a private
  // `external` INSTANCE native (instance, not @JvmStatic, so the native binds as a plain method).
  private def writeStaticsMember(w: IndentWriter, ident: Ident, m: Interface.Method) {
    val name = idJava.method(m.ident)
    val rawName = name + "_native"
    val params = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
    val argList = m.params.map(p => idJava.local(p.ident)).mkString(", ")
    val nonNull = m.ret.exists(t => isInterface(t.resolved))

    w.wl
    writeMethodDoc(w, m, idJava.local)
    if (m.ret.isEmpty) {
      w.w(s"override fun $name($params)").braced {
        w.wl(s"$rawName($argList)")
      }
    } else if (nonNull) {
      val t = marshal.returnTypeNonNull(m.ret)
      w.wl(s"override fun $name($params): $t =")
      w.nested {
        w.wl(s"$rawName($argList) ?: throw IllegalStateException(${q(ident.name + "." + name + " returned null")})")
      }
    } else {
      w.wl(s"override fun $name($params)${retSuffix(m.ret)} = $rawName($argList)")
    }
    w.wl(s"private external fun $rawName($params)${retSuffix(m.ret)}")
  }

  // Source-compat shim: companion extensions so old `<Name>.<static>(...)` call sites keep compiling
  // against the new API (Kotlin; needs the import). Plain -- intentionally NOT @Deprecated: the team
  // marks these via their own lint rule + baseline, so codegen imposes no deprecation policy. Lives in
  // impl (delegates to the Cpp<Name>Statics facade); same package as the generated types.
  private def generateStaticsCompatExtensions(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface, statics: Seq[Interface.Method]) {
    val self = marshal.typename(ident, i)
    val impl = "Cpp" + self + "Statics"
    writeKotlinFile(implFolder, self + "StaticsCompat.kt", origin, Nil, w => {
      w.wl(s"// Source-compat extensions: old `$self.<static>(...)` call sites keep compiling (Kotlin; needs")
      w.wl(s"// the import). Backed by one lazy(NONE) $impl -- no synchronized check on hot static calls;")
      w.wl(s"// idempotent init + stateless delegator, so a first-call race is harmless.")
      w.wl(s"private val instance: ${self}Statics by lazy(LazyThreadSafetyMode.NONE) { $impl() }")
      for (m <- statics) {
        val name = idJava.method(m.ident)
        val params = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
        val argList = m.params.map(p => idJava.local(p.ident)).mkString(", ")
        w.wl
        w.wl(s"fun $self.Companion.$name($params)${staticReturnType(m)} = instance.$name($argList)")
      }
    })
  }

  private def generateInterfaceCppProxy(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface) {
    val self = marshal.typename(ident, i)
    val proxy = "Cpp" + self
    val tpl = kotlinTypeParams(typeParams)
    val imports = List(
      "com.snapchat.djinni.NativeObjectManager",
      "java.util.concurrent.atomic.AtomicBoolean")

    writeKotlinFile(implFolder, proxy + ".kt", origin, imports, w => {
      w.wl("// CppProxy for " + self + " -- wraps a native C++ implementation. Instance methods only;")
      w.wl("// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members")
      w.wl("// the JNI layer / support-lib bind to. Static factories live on Cpp" + self + "Statics.")
      w.w(s"class $proxy$tpl private constructor(private val nativeRef: Long) : $self$tpl").braced {
        w.wl("private val destroyed = AtomicBoolean(false)")
        w.wl
        w.w("init").braced {
          w.wl("if (nativeRef == 0L) throw RuntimeException(\"nativeRef is zero\")")
          w.wl("NativeObjectManager.register(this, nativeRef)")
        }

        val (props, plain) = interfaceAccessors(i)
        // Property overrides: computed get()/set() delegating to the UNCHANGED native_* methods.
        for ((g, sOpt) <- props) {
          val ty = marshal.returnType(g.ret)
          val getNative = "native_" + idJava.method(g.ident)
          w.wl
          w.wl(s"override ${if (sOpt.isDefined) "var" else "val"} ${propName(g)}: $ty")
          w.nested {
            w.w("get()").braced {
              w.wl("assert(!destroyed.get()) { \"trying to use a destroyed object\" }")
              w.wl(s"return $getNative(nativeRef)")
            }
            for (s <- sOpt) {
              val setNative = "native_" + idJava.method(s.ident)
              w.w("set(value)").braced {
                w.wl("assert(!destroyed.get()) { \"trying to use a destroyed object\" }")
                w.wl(s"$setNative(nativeRef, value)")
              }
            }
          }
          w.wl(s"private external fun $getNative(_nativeRef: Long): $ty")
          for (s <- sOpt) {
            val setNative = "native_" + idJava.method(s.ident)
            w.wl(s"private external fun $setNative(_nativeRef: Long, value: ${marshal.paramType(s.params.head.ty)})")
          }
        }
        // Plain method overrides.
        for (m <- plain) {
          val name = idJava.method(m.ident)
          val nativeName = "native_" + name
          val params = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
          val nativeParams = ("_nativeRef: Long" +: m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}")).mkString(", ")
          val callArgs = ("nativeRef" +: m.params.map(p => idJava.local(p.ident))).mkString(", ")
          w.wl
          w.w(s"override fun $name($params)${retSuffix(m.ret)}").braced {
            w.wl("assert(!destroyed.get()) { \"trying to use a destroyed object\" }")
            val ret = if (m.ret.isEmpty) "" else "return "
            w.wl(s"$ret$nativeName($callArgs)")
          }
          w.wl(s"private external fun $nativeName($nativeParams)${retSuffix(m.ret)}")
        }

        w.wl
        w.w("companion object").braced {
          w.wl("@JvmStatic")
          w.wl("external fun nativeDestroy(nativeRef: Long)")
        }
      }
    })
  }

  // ==============================================================================================
  // Constants (best-effort; not on the JNI critical path and not exercised by the PoC sample).
  // ==============================================================================================
  private def writeKotlinConsts(w: IndentWriter, consts: Seq[Const]) {
    for (c <- consts) {
      writeDoc(w, c.doc)
      val ty = marshal.fieldType(c.ty)
      val isCompileTimeConst = c.ty.resolved.base match {
        case _: MPrimitive => true
        case MString => true
        case _ => false
      }
      val prefix = if (isCompileTimeConst) "const val" else "val"
      w.w(s"$prefix ${idJava.const(c.ident)}: $ty = ")
      writeKotlinConstValue(w, c.ty, c.value)
      w.wl
    }
  }

  private def writeKotlinConstValue(w: IndentWriter, ty: TypeRef, v: Any): Unit = v match {
    // Strip a trailing `?` so an OPTIONAL i64/f32 constant (field type "Long?"/"Float?") still gets the
    // L/f suffix -- without it the literal is typed Double/Int and fails against the Long?/Float? slot.
    case l: Long if marshal.fieldType(ty).stripSuffix("?").equalsIgnoreCase("long") => w.w(l.toString + "L")
    case l: Long => w.w(l.toString)
    case d: Double if marshal.fieldType(ty).stripSuffix("?").equalsIgnoreCase("float") => w.w(d.toString + "f")
    case d: Double => w.w(d.toString)
    case b: Boolean => w.w(if (b) "true" else "false")
    case s: String => w.w(s)
    case e: EnumValue => w.w(s"${marshal.typename(ty)}.${idJava.enum(e)}")
    case v: ConstRef => w.w(idJava.const(v))
    case z: Map[_, _] => // composite record value
      val recordMdef = ty.resolved.base.asInstanceOf[MDef]
      val record = recordMdef.body.asInstanceOf[Record]
      val vMap = z.asInstanceOf[Map[String, Any]]
      w.wl(s"${marshal.typename(ty)}(")
      w.nested {
        val skipFirst = SkipFirst()
        for (f <- record.fields) {
          skipFirst { w.wl(",") }
          w.w(s"${idJava.field(f.ident)} = ")
          writeKotlinConstValue(w, f.ty, vMap.apply(f.ident.name))
        }
        w.wl
      }
      w.w(")")
  }
}
