/**
  * Copyright 2014 Dropbox, Inc.
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  *
  *    http://www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an "AS IS" BASIS,
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
  *
  * Kotlin backend (PoC). Modeled on JavaGenerator. JavaGenerator/JavaMarshal are NOT modified.
  */

package djinni

import java.io.File

import djinni.ast.Record.DerivingType
import djinni.ast._
import djinni.generatorTools._
import djinni.meta._
import djinni.writer.IndentWriter

// Emits an idiomatic Kotlin surface alongside (never replacing) the Java backend.
//
// Layout -- the API/impl split, by construction:
//   <kotlin-out>/api/<Name>.kt         pure declarations: enum class / data class / interface.
//                                       No JNI, no `external`, no NativeObjectManager -> compiles in a
//                                       pure-JVM module with no native dependency.
//   <kotlin-out>/impl/<Name>CppProxy.kt the CppProxy: `external` native methods, nativeRef + destroyed
//                                       lifetime, NativeObjectManager registration. Depends on the API
//                                       + the support-lib only.
//
// JVM-name parity: type/field/method/enum names all come from the Java ident style (idJava), so the
// member surface matches today's generated Java and the existing JNI layer keeps binding. The
// intentional deltas are: idiomatic type shapes + nullability, the api/impl file split, and a non-null
// create(). See IMPLEMENTATION-NOTES.md for the exact JNI-side implications of the last two.
class KotlinGenerator(spec: Spec) extends Generator(spec) {

  val marshal = new KotlinMarshal(spec)

  private val apiFolder = new File(spec.kotlinOutFolder.get, "api")
  private val implFolder = new File(spec.kotlinOutFolder.get, "impl")

  private def writeKotlinFile(folder: File, fileName: String, origin: String, imports: Iterable[String], f: IndentWriter => Unit) {
    if (!spec.skipGeneration) {
      createFolder("Kotlin", folder)
    }
    createFile(folder, fileName, (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      spec.kotlinPackage.foreach(p => w.wl(s"package $p").wl)
      if (imports.nonEmpty) {
        imports.foreach(i => w.wl(s"import $i"))
        w.wl
      }
      f(w)
    })
  }

  private def kotlinTypeParams(params: Seq[TypeParam]): String =
    if (params.isEmpty) "" else params.map(p => idJava.typeParam(p.ident)).mkString("<", ", ", ">")

  // ": Type" for a return, or "" for void (idiomatic Kotlin omits `: Unit`).
  private def retSuffix(ret: Option[TypeRef]): String = ret.fold("")(t => ": " + marshal.returnType(Some(t)))

  // ==============================================================================================
  // Enum -> enum class (pure API). Standard JVM enum: values()/valueOf()/ordinal()/name() are
  // identical to a Java enum, so the JNI JniEnum helper binds unchanged.
  // ==============================================================================================
  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: Enum) {
    writeKotlinFile(apiFolder, idJava.ty(ident) + ".kt", origin, Nil, w => {
      writeDoc(w, doc)
      w.w(s"enum class ${marshal.typename(ident, e)}").braced {
        // Only "normal" options become constants; NoFlags/AllFlags are synthesized via EnumSet in
        // types, exactly as the Java backend does.
        for (o <- normalEnumOptions(e)) {
          writeDoc(w, o.doc)
          w.wl(idJava.enum(o.ident) + ",")
        }
      }
    })
  }

  // ==============================================================================================
  // Record -> data class (pure API). Fields use the idiomatic read-only collection flavor
  // (List/Set/Map, via KotlinMarshal.fieldType(concrete=false)) and boxed optionals (T?). This is
  // the team's idiomatic-surface decision: collections are read-only interfaces everywhere and only
  // arrays stay mutable. The JNI record marshalling then binds the collection *interface* descriptors
  // (Ljava/util/List; etc.) rather than concrete java.util.* -- a deferred JNI-side change tracked in
  // IMPLEMENTATION-NOTES, not a surface blocker.
  // ==============================================================================================
  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record) {
    // Mirror JavaGenerator's extended-record naming so the class name matches (ABI).
    val name = if (r.ext.java) ident.name + "_base" else ident.name
    val self = marshal.typename(name, r)
    val tpl = kotlinTypeParams(params)

    writeKotlinFile(apiFolder, idJava.ty(name) + ".kt", origin, Nil, w => {
      writeDoc(w, doc)

      val interfaces = scala.collection.mutable.ArrayBuffer[String]()
      if (r.derivingTypes.contains(DerivingType.Ord)) interfaces += s"Comparable<$self$tpl>"
      val impl = if (interfaces.isEmpty) "" else " : " + interfaces.mkString(", ")

      if (r.fields.isEmpty) {
        // Kotlin forbids a data class with no constructor params; emit a plain class (matches an
        // empty Java record's zero-arg constructor).
        w.w(s"class $self$tpl$impl").braced {
          generateRecordConsts(w, self, r.consts)
        }
      } else {
        w.wl(s"data class $self$tpl(")
        w.nested {
          for (f <- r.fields) {
            writeDoc(w, f.doc)
            w.wl(s"val ${idJava.field(f.ident)}: ${marshal.fieldType(f.ty)},")
          }
        }
        if (r.consts.nonEmpty || r.derivingTypes.contains(DerivingType.Ord)) {
          w.w(s")$impl").braced {
            if (r.derivingTypes.contains(DerivingType.Ord)) generateCompareTo(w, self + tpl, r)
            generateRecordConsts(w, self, r.consts)
          }
        } else {
          w.wl(s")$impl")
        }
      }
    })
  }

  // deriving(ord) -> Comparable<Self>.compareTo. Mirrors JavaGenerator's field-by-field ordering:
  // compare each field in declaration order, returning at the first non-equal field. Every field type
  // that reaches here is Comparable in Kotlin -- primitives (Byte/Short/Int/Long/Float/Double), String,
  // enums, java.util.Date / java.time.Duration externs, and nested ord records (whose generated
  // compareTo we recurse into) -- so a uniform `.compareTo` gives the natural order Java produces.
  private def generateCompareTo(w: IndentWriter, selfWithTpl: String, r: Record) {
    w.wl
    w.w(s"override fun compareTo(other: $selfWithTpl): Int").braced {
      w.wl("var tempResult: Int")
      for (f <- r.fields) {
        val name = idJava.field(f.ident)
        w.wl(s"tempResult = this.$name.compareTo(other.$name)")
        w.w("if (tempResult != 0)").braced {
          w.wl("return tempResult")
        }
      }
      w.wl("return 0")
    }
  }

  private def generateRecordConsts(w: IndentWriter, self: String, consts: Seq[Const]) {
    if (consts.isEmpty) return
    w.wl
    w.w("companion object").braced {
      writeKotlinConsts(w, consts)
    }
  }

  // ==============================================================================================
  // Interface -> `interface` (pure API) + a separate CppProxy (impl).
  // ==============================================================================================
  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface) {
    val statics = i.methods.filter(m => m.static && m.lang.java)
    val createOnly = createOnlyFactory(ident, i)
    // A util (static-only) type has no instance surface: skip the (empty) instance interface -- its
    // statics service takes the plain <Name> instead (generateStaticsApi below).
    if (!isUtilInterface(ident, i)) generateInterfaceApi(origin, ident, doc, typeParams, i)
    // A "create-only" type has NO public <Name>Statics -- its create() is reached ONLY via the Companion
    // hatch (legacy) and the suspend AudioCoreProviders. Types with REAL statics (mixed create+others, or
    // non-create statics) keep the injectable service (<Name>Statics sidecar, or plain <Name> for util),
    // which the provider also exposes.
    if (statics.nonEmpty && createOnly.isEmpty) generateStaticsApi(origin, ident, doc, typeParams, i, statics)
    if (i.ext.cpp) {
      generateInterfaceCppProxy(origin, ident, doc, typeParams, i)
      if (statics.nonEmpty) {
        generateStaticsImpl(origin, ident, doc, typeParams, i, statics, createOnly)
        generateStaticsCompatExtensions(origin, ident, doc, typeParams, i, statics, createOnly)
      }
    }
  }

  // --- Property synthesis: getX()/isX()/setX() accessor methods on an interface become Kotlin
  // val/var properties, so callers write `obj.sampleRate` (matching data-class access + how the old
  // Java API read via Kotlin synthetic properties). The native_* methods are emitted UNCHANGED, so
  // the JNI binding is untouched -- only the public surface becomes a property. Conservative: only
  // no-arg get_*/is_* (getter), paired with a single-arg void set_* of matching type (-> var).
  // Detection works off the NORMALIZED Java method name (idJava.method), so BOTH snake_case IDL
  // (`get_foo`/`is_x`/`set_foo`) AND camelCase IDL (`getFoo`/`isX`/`setFoo`) are recognized as
  // accessors -- exactly matching how the old Java binding + Kotlin synthetic properties exposed
  // every such method as `obj.foo` / `obj.isX` (which is what the existing call sites use). The
  // charAt-after-prefix .isUpper guard excludes non-accessors like `setup()`/`island()`/`getaway()`.
  private def jName(m: Interface.Method): String = idJava.method(m.ident)
  private def isGetterName(jn: String): Boolean =
    (jn.length > 3 && jn.startsWith("get") && jn.charAt(3).isUpper) ||
    (jn.length > 2 && jn.startsWith("is")  && jn.charAt(2).isUpper)
  private def isSetterName(jn: String): Boolean =
    jn.length > 3 && jn.startsWith("set") && jn.charAt(3).isUpper
  private def isGetterM(m: Interface.Method): Boolean =
    !m.static && m.params.isEmpty && m.ret.isDefined && isGetterName(jName(m))
  private def isSetterM(m: Interface.Method): Boolean =
    !m.static && m.params.length == 1 && m.ret.isEmpty && isSetterName(jName(m))
  private def accBase(m: Interface.Method): String = {
    val jn = jName(m)
    if (jn.startsWith("get") || jn.startsWith("set")) jn.substring(3) else jn.substring(2)
  }
  private def propName(g: Interface.Method): String = {
    val jn = jName(g)
    if (jn.startsWith("get")) { val s = jn.substring(3); s.head.toLower.toString + s.tail } else jn
  }
  private def interfaceAccessors(i: Interface): (Seq[(Interface.Method, Option[Interface.Method])], Seq[Interface.Method]) = {
    val instance = i.methods.filter(m => !m.static)
    val setterByBase = instance.filter(isSetterM).map(s => accBase(s) -> s).toMap
    val props = instance.filter(isGetterM).map { g =>
      val s = setterByBase.get(accBase(g)).filter(st => marshal.paramType(st.params.head.ty) == marshal.returnType(g.ret))
      (g, s)
    }
    val consumed = props.flatMap { case (g, s) => g +: s.toSeq }.toSet
    (props, instance.filterNot(consumed.contains))
  }

  private def generateInterfaceApi(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface) {
    val self = marshal.typename(ident, i)
    val tpl = kotlinTypeParams(typeParams)

    writeKotlinFile(apiFolder, idJava.ty(ident) + ".kt", origin, Nil, w => {
      writeDoc(w, doc)
      w.w(s"interface $self$tpl").braced {
        // Accessor methods (get_/is_/set_) become val/var properties; everything else stays a fun.
        // Static factories do NOT live here -- they're on the injectable <Name>Statics.
        val (props, plain) = interfaceAccessors(i)
        for ((g, sOpt) <- props) {
          writeMethodDoc(w, g, idJava.local)
          w.wl(s"${if (sOpt.isDefined) "var" else "val"} ${propName(g)}: ${marshal.returnType(g.ret)}")
        }
        for (m <- plain) {
          writeMethodDoc(w, m, idJava.local)
          val params = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
          w.wl(s"fun ${idJava.method(m.ident)}($params)${retSuffix(m.ret)}")
        }

        // create-only interface whose create() takes params -> expose a raw, framework-agnostic nested
        // Factory (contract only, no DI annotations). The DI graph (engine-impl) satisfies it by
        // delegating to the cached create(...); it is also generally useful (impl code, tests). A
        // no-arg create-only needs no factory -- it is a direct graph accessor.
        createOnlyFactory(ident, i).filter(_.params.nonEmpty).foreach { m =>
          val fParams = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
          w.wl
          w.w("interface Factory").braced {
            w.wl(s"fun ${idJava.method(m.ident)}($fParams): ${marshal.returnTypeNonNull(m.ret)}")
          }
        }

        // Constants stay on the API interface. Also emit an (otherwise empty) companion when the
        // interface has statics -- it's the anchor the @Deprecated source-compat extensions attach to,
        // keeping the old `<Name>.<static>(...)` call syntax compiling.
        val hasStatics = i.methods.exists(m => m.static && m.lang.java)
        if (i.consts.nonEmpty || hasStatics) {
          w.wl
          w.w("companion object").braced {
            writeKotlinConsts(w, i.consts)
          }
        }
      }
    })
  }

  // Statics-as-service. A djinni interface `static` (create, ...) is exposed NOT as a language static
  // but as an instance method on an injectable service:
  //   api:  interface <Name>Statics    { fun create(...): <Name>; ... }
  //   impl: class Cpp<Name>Statics : <Name>Statics { init { <inject init> }  ...private external... }
  // Call sites depend on the interface (mockable in tests). The `external` natives are private INSTANCE
  // members of the impl, reachable only via a Cpp<Name>Statics instance -- so constructing that
  // instance is the single init chokepoint.

  // A `create()` factory returns a freshly-constructed instance of its own interface, so it is
  // non-null. STRICTLY only that: static, named exactly `create`, returning the declaring (self)
  // type. Every other static -- accessors like `getVisualEq()`, openers like `open()`, or factories
  // returning a *different* interface (e.g. `getEffectMetadataManager()`) -- can legitimately be
  // null, so they keep the mirrored (nullable) policy.
  private def isSelfCreateFactory(m: Interface.Method, ident: Ident): Boolean =
    m.static && m.ident.name == "create" && m.ret.exists { t =>
      t.resolved.base match {
        case d: MDef => d.defType == DInterface && d.name == ident.name
        case _ => false
      }
    }

  // A "create-only" interface has EXACTLY one static and it is the strict self create() factory.
  // Such types get idiomatic DI-first construction (a graph accessor for no-arg create(), or a raw
  // nested Factory for arg-taking create()) instead of the injectable <Name>Statics service. Mixed
  // types (create() + other statics) keep the full Statics service untouched.
  private def createOnlyFactory(ident: Ident, i: Interface): Option[Interface.Method] =
    i.methods.filter(m => m.static && m.lang.java) match {
      case Seq(m) if isSelfCreateFactory(m, ident) => Some(m)
      case _ => None
    }

  // A "utility" interface has static functions but NO instance (member) functions -- e.g. MusicUtils.
  // Splitting <Name> + <Name>Statics only makes sense when a type has BOTH; a static-only type has no
  // instance surface worth generating, so its injectable service takes the PLAIN <Name> (MusicUtils),
  // the (otherwise empty) instance interface is suppressed, and its CppProxy loses the interface
  // supertype (it becomes a bare native-handle holder the JNI still binds to). create-only types are
  // handled separately and excluded here.
  private def isUtilInterface(ident: Ident, i: Interface): Boolean =
    createOnlyFactory(ident, i).isEmpty &&
      i.methods.exists(m => m.static && m.lang.java) &&
      !i.methods.exists(m => !m.static && m.lang.java)

  // Public name of the injectable statics service: plain <Name> for a util (static-only) interface,
  // else the <Name>Statics sidecar beside the instance <Name>.
  private def staticsServiceName(ident: Ident, i: Interface): String = {
    val self = marshal.typename(ident, i)
    if (isUtilInterface(ident, i)) self else self + "Statics"
  }

  // Provider accessor for a statics service: `musicUtils()` for a util, `audioEngineCommonStatics()`
  // for a sidecar.
  private def staticsAccessorName(ident: Ident, i: Interface): String = {
    val self = marshal.typename(ident, i)
    if (isUtilInterface(ident, i)) lowerFirst(self) else lowerFirst(self) + "Statics"
  }

  // ": T" for the statics service signature: a self `create()` is non-null; other statics keep the
  // mirrored policy type; void -> "".
  private def staticReturnType(m: Interface.Method, ident: Ident): String =
    if (m.ret.isEmpty) ""
    else if (isSelfCreateFactory(m, ident)) ": " + marshal.returnTypeNonNull(m.ret)
    else retSuffix(m.ret)

  private def generateStaticsApi(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface, statics: Seq[Interface.Method]) {
    val self = marshal.typename(ident, i)
    val util = isUtilInterface(ident, i)
    val svc = staticsServiceName(ident, i) // plain <Name> for util, else <Name>Statics sidecar
    writeKotlinFile(apiFolder, svc + ".kt", origin, Nil, w => {
      if (util) {
        // Static-only type: this service IS the public <Name>, so it carries the interface doc + the
        // Companion (consts + source-compat hatch anchor) the suppressed instance interface would have.
        writeDoc(w, doc)
        w.wl(s"// Static-only utility surface, exposed as an injectable service (no language-level statics).")
      } else {
        w.wl(s"// Injectable statics service for $self (replaces language-level statics).")
      }
      w.wl(s"// Depend on THIS at call sites so the native surface stays hidden and mockable; a real")
      w.wl(s"// instance comes from Cpp${self}Statics (impl), whose construction is the init gate.")
      w.w(s"interface $svc").braced {
        for (m <- statics) {
          writeMethodDoc(w, m, idJava.local)
          val params = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
          w.wl(s"fun ${idJava.method(m.ident)}($params)${staticReturnType(m, ident)}")
        }
        if (util) {
          w.wl
          w.w("companion object").braced {
            writeKotlinConsts(w, i.consts)
          }
        }
      }
    })
  }

  private def generateStaticsImpl(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface, statics: Seq[Interface.Method], createOnly: Option[Interface.Method]) {
    val self = marshal.typename(ident, i)
    val impl = "Cpp" + self + "Statics"
    // create-only: NO public <Name>Statics interface -- this internal class is just the native-create
    // factory (the JNI binds create_native here), used only by the Companion hatch + AudioCoreProviders.
    // real-statics: implements the public <Name>Statics service.
    val superType = if (createOnly.isDefined) "" else s" : ${staticsServiceName(ident, i)}"
    writeKotlinFile(implFolder, impl + ".kt", origin, Nil, w => {
      w.wl(s"// Internal singleton for the $self static surface -- never visible to consumers. Reached only")
      w.wl(s"// via the Companion hatch (legacy) + AudioCoreProviders. Stateless facade over the native")
      w.wl(s"// statics; readiness gating lives at those seams (AudioCoreInit), not here.")
      w.w(s"internal object $impl$superType").braced {
        for (m <- statics) {
          writeStaticsMember(w, ident, m, createOnly.isEmpty)
        }
      }
    })
  }

  // One statics member: a public `override` wrapper (non-null + throw for factories) over a private
  // `external` INSTANCE native (instance, not @JvmStatic, so the native binds as a plain method).
  private def writeStaticsMember(w: IndentWriter, ident: Ident, m: Interface.Method, isOverride: Boolean) {
    val name = idJava.method(m.ident)
    val rawName = name + "_native"
    val params = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
    val argList = m.params.map(p => idJava.local(p.ident)).mkString(", ")
    val nonNull = isSelfCreateFactory(m, ident)
    // create-only: no <Name>Statics interface to override; real-statics: `override`.
    val ov = if (isOverride) "override " else ""

    w.wl
    writeMethodDoc(w, m, idJava.local)
    if (m.ret.isEmpty) {
      w.w(s"${ov}fun $name($params)").braced {
        w.wl(s"$rawName($argList)")
      }
    } else if (nonNull) {
      val t = marshal.returnTypeNonNull(m.ret)
      w.wl(s"${ov}fun $name($params): $t =")
      w.nested {
        w.wl(s"$rawName($argList) ?: throw IllegalStateException(${q(ident.name + "." + name + " returned null")})")
      }
    } else {
      w.wl(s"${ov}fun $name($params)${retSuffix(m.ret)} = $rawName($argList)")
    }
    w.wl(s"private external fun $rawName($params)${retSuffix(m.ret)}")
  }

  // Source-compat shim: companion extensions so old `<Name>.<static>(...)` call sites keep compiling
  // against the new API (Kotlin; needs the import). Plain -- intentionally NOT @Deprecated: the team
  // marks these via their own lint rule + baseline, so codegen imposes no deprecation policy. Lives in
  // impl (delegates to the Cpp<Name>Statics facade); same package as the generated types.
  // lower-cases the first char: "Arpeggiator" -> "arpeggiator". Used for the shared statics-instance
  // name and the AudioCoreProviders accessor names.
  private def lowerFirst(s: String): String = if (s.isEmpty) s else s.head.toLower.toString + s.tail
  private def generateStaticsCompatExtensions(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface, statics: Seq[Interface.Method], createOnly: Option[Interface.Method]) {
    val self = marshal.typename(ident, i)
    val impl = "Cpp" + self + "Statics"
    writeKotlinFile(implFolder, self + "StaticsCompat.kt", origin, List("kotlinx.coroutines.runBlocking"), w => {
      w.wl(s"// Source-compat hatch: old `$self.<static>(...)` call sites keep compiling -- now init-SAFE.")
      w.wl(s"// Each hatch blocks on AudioCore readiness before touching the native surface, so a pre-init")
      w.wl(s"// call WAITS instead of crashing (old code pays with a blocked thread; new code should migrate")
      w.wl(s"// to the suspend AudioCoreProviders). Delegates to the internal $impl singleton (also reused")
      w.wl(s"// by AudioCoreProvidersImpl).")
      for (m <- statics) {
        val name = idJava.method(m.ident)
        val params = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
        val argList = m.params.map(p => idJava.local(p.ident)).mkString(", ")
        w.wl
        w.w(s"fun $self.Companion.$name($params)${staticReturnType(m, ident)}").braced {
          w.wl("runBlocking { AudioCoreInit.awaitReady() }")
          val ret = if (m.ret.isEmpty) "" else "return "
          w.wl(s"$ret$impl.$name($argList)")
        }
      }
    })
  }

  private def generateInterfaceCppProxy(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface) {
    val self = marshal.typename(ident, i)
    val proxy = "Cpp" + self
    val tpl = kotlinTypeParams(typeParams)
    val imports = List(
      "com.snapchat.djinni.NativeObjectManager",
      "java.util.concurrent.atomic.AtomicBoolean")

    // A util (static-only) type has no instance interface, so its proxy is a bare native-handle holder
    // (no supertype); the JNI still binds its (long) constructor + nativeDestroy(long). Otherwise the
    // proxy implements the instance interface <Name>.
    val superType = if (isUtilInterface(ident, i)) "" else s" : $self$tpl"
    writeKotlinFile(implFolder, proxy + ".kt", origin, imports, w => {
      w.wl("// CppProxy for " + self + " -- wraps a native C++ implementation. Instance methods only;")
      w.wl("// the (long) constructor, native_* methods and nativeDestroy(long) are the exact JVM members")
      w.wl("// the JNI layer / support-lib bind to. Static factories live on Cpp" + self + "Statics.")
      w.w(s"internal class $proxy$tpl private constructor(private val nativeRef: Long)$superType").braced {
        w.wl("private val destroyed = AtomicBoolean(false)")
        w.wl
        w.w("init").braced {
          w.wl("if (nativeRef == 0L) throw RuntimeException(\"nativeRef is zero\")")
          w.wl("NativeObjectManager.register(this, nativeRef)")
        }

        val (props, plain) = interfaceAccessors(i)
        // Property overrides: computed get()/set() delegating to the UNCHANGED native_* methods.
        for ((g, sOpt) <- props) {
          val ty = marshal.returnType(g.ret)
          val getNative = "native_" + idJava.method(g.ident)
          w.wl
          w.wl(s"override ${if (sOpt.isDefined) "var" else "val"} ${propName(g)}: $ty")
          w.nested {
            w.w("get()").braced {
              w.wl("assert(!destroyed.get()) { \"trying to use a destroyed object\" }")
              w.wl(s"return $getNative(nativeRef)")
            }
            for (s <- sOpt) {
              val setNative = "native_" + idJava.method(s.ident)
              w.w("set(value)").braced {
                w.wl("assert(!destroyed.get()) { \"trying to use a destroyed object\" }")
                w.wl(s"$setNative(nativeRef, value)")
              }
            }
          }
          w.wl(s"private external fun $getNative(_nativeRef: Long): $ty")
          for (s <- sOpt) {
            val setNative = "native_" + idJava.method(s.ident)
            w.wl(s"private external fun $setNative(_nativeRef: Long, value: ${marshal.paramType(s.params.head.ty)})")
          }
        }
        // Plain method overrides.
        for (m <- plain) {
          val name = idJava.method(m.ident)
          val nativeName = "native_" + name
          val params = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
          val nativeParams = ("_nativeRef: Long" +: m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}")).mkString(", ")
          val callArgs = ("nativeRef" +: m.params.map(p => idJava.local(p.ident))).mkString(", ")
          w.wl
          w.w(s"override fun $name($params)${retSuffix(m.ret)}").braced {
            w.wl("assert(!destroyed.get()) { \"trying to use a destroyed object\" }")
            val ret = if (m.ret.isEmpty) "" else "return "
            w.wl(s"$ret$nativeName($callArgs)")
          }
          w.wl(s"private external fun $nativeName($nativeParams)${retSuffix(m.ret)}")
        }

        w.wl
        w.w("companion object").braced {
          w.wl("@JvmStatic")
          w.wl("external fun nativeDestroy(nativeRef: Long)")
        }
      }
    })
  }

  // ==============================================================================================
  // Constants (best-effort; not on the JNI critical path and not exercised by the PoC sample).
  // ==============================================================================================
  private def writeKotlinConsts(w: IndentWriter, consts: Seq[Const]) {
    for (c <- consts) {
      writeDoc(w, c.doc)
      val ty = marshal.fieldType(c.ty)
      val isCompileTimeConst = c.ty.resolved.base match {
        case _: MPrimitive => true
        case MString => true
        case _ => false
      }
      val prefix = if (isCompileTimeConst) "const val" else "val"
      w.w(s"$prefix ${idJava.const(c.ident)}: $ty = ")
      writeKotlinConstValue(w, c.ty, c.value)
      w.wl
    }
  }

  private def writeKotlinConstValue(w: IndentWriter, ty: TypeRef, v: Any): Unit = v match {
    // Strip a trailing `?` so an OPTIONAL i64/f32 constant (field type "Long?"/"Float?") still gets the
    // L/f suffix -- without it the literal is typed Double/Int and fails against the Long?/Float? slot.
    case l: Long if marshal.fieldType(ty).stripSuffix("?").equalsIgnoreCase("long") => w.w(l.toString + "L")
    case l: Long => w.w(l.toString)
    case d: Double if marshal.fieldType(ty).stripSuffix("?").equalsIgnoreCase("float") => w.w(d.toString + "f")
    case d: Double => w.w(d.toString)
    case b: Boolean => w.w(if (b) "true" else "false")
    case s: String => w.w(s)
    case e: EnumValue => w.w(s"${marshal.typename(ty)}.${idJava.enum(e)}")
    case v: ConstRef => w.w(idJava.const(v))
    case z: Map[_, _] => // composite record value
      val recordMdef = ty.resolved.base.asInstanceOf[MDef]
      val record = recordMdef.body.asInstanceOf[Record]
      val vMap = z.asInstanceOf[Map[String, Any]]
      w.wl(s"${marshal.typename(ty)}(")
      w.nested {
        val skipFirst = SkipFirst()
        for (f <- record.fields) {
          skipFirst { w.wl(",") }
          w.w(s"${idJava.field(f.ident)} = ")
          writeKotlinConstValue(w, f.ty, vMap.apply(f.ident.name))
        }
        w.wl
      }
      w.w(")")
  }

  // ============================================================================================
  // Async DI surface (generated; NO DI framework on the engine side). Our provider surface is FLAT
  // -- each provider is just `await readiness -> create()`, no cross-deps -- so we emit a plain
  // interface + a plain object impl, indistinguishable to a downstream Metro graph that @Includes it.
  // Providers are `suspend` so injection can await native-lib readiness (AudioCoreInit) without
  // blocking; a downstream graph (with Metro suspend-providers) turns each accessor into an async
  // binding. Emits three files:
  //   engine-api : interface AudioCoreProviders { suspend fun <name>(): <T | T.Factory> }
  //   engine-impl: object AudioCoreInit (CompletableDeferred readiness gate)
  //   engine-impl: internal object AudioCoreProvidersImpl + public fun audioCoreProviders()
  // ============================================================================================
  override def generateModule(decls: Seq[InternTypeDecl]): Unit = {
    val interfaces = decls.flatMap { td =>
      td.body match { case i: Interface if i.ext.cpp => Some((td.ident, i)); case _ => None }
    }
    // ① / ② create-only -> suspend fun x() / xFactory(); ③ real statics -> suspend fun xStatics(): XStatics.
    val createOnly = interfaces.flatMap { case (ident, i) => createOnlyFactory(ident, i).map(m => (ident, i, m)) }
    val realStatics = interfaces.filter { case (ident, i) =>
      createOnlyFactory(ident, i).isEmpty && i.methods.exists(m => m.static && m.lang.java)
    }
    if (createOnly.isEmpty && realStatics.isEmpty) return
    val origin = decls.head.origin

    // accessor name: no-arg create -> `arpeggiator`; arg-taking create -> `transportFactory`.
    def accessor(self: String, m: Interface.Method): String =
      if (m.params.isEmpty) lowerFirst(self) else lowerFirst(self) + "Factory"
    def providerType(self: String, m: Interface.Method): String =
      if (m.params.isEmpty) self else s"$self.Factory"

    // --- api: the plain suspend-provider interface (contract). `suspend` needs only stdlib. --------
    writeKotlinFile(apiFolder, "AudioCoreProviders.kt", origin, Nil, w => {
      w.wl("// Async DI surface for the audio engine (generated). Each provider is `suspend` so injection")
      w.wl("// can await native readiness (AudioCoreInit) without blocking. Plain Kotlin -- NO DI framework")
      w.wl("// here; a downstream graph @Includes this and (with Metro suspend-providers) turns each")
      w.wl("// accessor into an async binding. Retrieve the impl via AudioCoreProviders.resolve().")
      w.w("interface AudioCoreProviders").braced {
        for ((ident, i, m) <- createOnly) {
          val self = marshal.typename(ident, i)
          w.wl(s"suspend fun ${accessor(self, m)}(): ${providerType(self, m)}")
        }
        for ((ident, i) <- realStatics) {
          w.wl(s"suspend fun ${staticsAccessorName(ident, i)}(): ${staticsServiceName(ident, i)}")
        }
        w.wl
        w.wl("companion object")
      }
    })

    // --- impl: the readiness gate. -----------------------------------------------------------------
    writeKotlinFile(implFolder, "AudioCoreInit.kt", origin, List("kotlinx.coroutines.CompletableDeferred"), w => {
      w.wl("// Readiness gate for the native audio-engine .so. The app calls markReady() once the")
      w.wl("// library is loaded + initialized (or markFailed(cause) on failure); every generated")
      w.wl("// provider / compat hatch awaits this before touching the native surface, so no native")
      w.wl("// call can run before the engine is ready.")
      w.w("object AudioCoreInit").braced {
        w.wl("private val ready = CompletableDeferred<Unit>()")
        w.wl
        w.wl("// Non-suspend snapshot: true once initialized SUCCESSFULLY (completed & not failed).")
        w.wl("val isReady: Boolean get() = ready.isCompleted && !ready.isCancelled")
        w.wl
        w.wl("// Suspends until the engine is ready; throws if initialization failed.")
        w.wl("suspend fun awaitReady() = ready.await()")
        w.wl
        w.wl("// Signal the .so is loaded + initialized. Idempotent (a later call is a no-op).")
        w.wl("fun markReady() { ready.complete(Unit) }")
        w.wl
        w.wl("// Signal initialization failed -- awaiters (and blocking hatches) throw `cause` instead")
        w.wl("// of hanging forever.")
        w.wl("fun markFailed(cause: Throwable) { ready.completeExceptionally(cause) }")
      }
    })

    // --- impl: hidden object impl + the resolve() retrieval extension. -----------------------------
    writeKotlinFile(implFolder, "AudioCoreProvidersImpl.kt", origin, Nil, w => {
      w.wl("// Impl of AudioCoreProviders (hidden -- consumers only see the interface + resolve()).")
      w.wl("// Each provider awaits AudioCoreInit, then delegates to the shared internal Cpp<name>Statics")
      w.wl("// singleton (the same statics facade the compat hatch uses). No Cpp* type is ever exposed.")
      w.w("internal object AudioCoreProvidersImpl : AudioCoreProviders").braced {
        val skipFirst = SkipFirst()
        for ((ident, i, m) <- createOnly) {
          skipFirst { w.wl }
          val self = marshal.typename(ident, i)
          val impl = "Cpp" + self + "Statics"
          if (m.params.isEmpty) {
            w.w(s"override suspend fun ${accessor(self, m)}(): $self").braced {
              w.wl("AudioCoreInit.awaitReady()")
              w.wl(s"return $impl.create()")
            }
          } else {
            val params = m.params.map(p => s"${idJava.local(p.ident)}: ${marshal.paramType(p.ty)}").mkString(", ")
            val args = m.params.map(p => idJava.local(p.ident)).mkString(", ")
            w.w(s"override suspend fun ${accessor(self, m)}(): $self.Factory").braced {
              w.wl("AudioCoreInit.awaitReady()")
              w.w(s"return object : $self.Factory").braced {
                w.wl(s"override fun create($params): $self = $impl.create($args)")
              }
            }
          }
        }
        for ((ident, i) <- realStatics) {
          skipFirst { w.wl }
          val self = marshal.typename(ident, i)
          val impl = "Cpp" + self + "Statics"
          w.w(s"override suspend fun ${staticsAccessorName(ident, i)}(): ${staticsServiceName(ident, i)}").braced {
            w.wl("AudioCoreInit.awaitReady()")
            w.wl(s"return $impl")
          }
        }
      }
      w.wl
      w.wl("// Retrieval (cheap; no construction) -- hand the interface to a downstream DI graph.")
      w.wl("fun AudioCoreProviders.Companion.resolve(): AudioCoreProviders = AudioCoreProvidersImpl")
    })
  }
}
